### ISSUE TITLE
Julia code blocks without executing code

### ISSUE THREAD

**Issue by omus** [JuliaDocs/Documenter.jl#109]
Since doctests use the julia code block syntax there is no way to write out arbitrary Julia code that uses the Julia syntax highlighting. For example with normal Markdown you could just write:

```
# Classic markdown
``julia
now(TimeZone("Europe/Warsaw"))
``
```
In order to get the equivalent with Documenter.jl I need to do:
```
# Documenter
``@example
using TimeZones  # hide
now(TimeZone("Europe/Warsaw"))
nothing  # hide
``
```

A more problematic example is I have some code I want to show to a user but don't actually want to run since it's rather slow to run:

```
# Classic Markdown
``julia
julia> using TimeZones

julia> TimeZones.Olson.compile(max_year=2200)

julia> ZonedDateTime(DateTime(2100), TimeZone("Europe/Warsaw"))
2100-01-01T00:00:00+01:00
``
```
Note: In my examples below I'm going to use two-backticks to denote a Markdown code block as using the normal three-backticks doesn't show nicely with GitHub syntax.

Maybe we should change the doctest syntax to be `jltest`(like in Base) or maybe `@doctest` to match the other Documenter.jl syntax.

**Comment by MichaelHatherly** [comment]
Yes, might be a good idea to make doctests explicit rather than implicit like they are currently.

I quite like the `@doctest` syntax. We can also automatically modify the `.language` field during rendering to change it to either `julia` or `jlcon` depending on whether it contains a `julia>` prompt to get correct highlighting.

**Comment by omus** [comment]
Definitely would be a breaking change. I'll note my currently work around is just to use an unhighlighted code block.

**Comment by MichaelHatherly** [comment]
> Definitely would be a breaking change.

Probably, though can be deprecated reasonably easily. We'd just have add some warnings and leave the old syntax intact for a little while.

**Comment by TotalVerb** [comment]
For the record, Currencies currently disables doctests for this reason. A similar issue is that REPL sessions like

    ```julia
    julia> 1 + 1
    2
    ```

are automatically doctests. This is a problem because Currencies makes use of `Dict`s, whose printing order is not stable from run to run.

**Comment by MichaelHatherly** [comment]
I think it's probably best to just switch to using `jldoctest` to mark code blocks as doctestable, and skip all `julia` and `jlcon` blocks. That's what `Base` is using and there's now a significant number of `jldoctest` blocks written, so probably best to just go with the flow for this. This would technically be a breaking change in the sense that packages using `julia` or `jlcon` won't have their doctests run (nothing should actually fail though), but probably best to just switch over sooner rather than later.

> order is not stable from run to run

I've also been bitten by the `Dict` printing myself, it's a bit unfortunate.

>  I would use jlcon but I don't think that highlighted well last time I checked.

Yeah, it seems to get confused with more complex blocks quite easily as far as I recall.
