### ISSUE TITLE
Document doctests using exceptions

### ISSUE THREAD

**Issue by omus** [JuliaDocs/Documenter.jl#110]
Documenter's doctests can handle exceptions but the documentation does not mention this feature at all. When attempting to use this feature I was unsure if I needed to include or exclude the stack trace:

Working example:
```
``@meta
DocTestSetup = quote
    using TimeZones
    warsaw = TimeZone("Europe/Warsaw")
end
``

``julia
julia> ZonedDateTime(DateTime(2014,3,30,1), warsaw)
2014-03-30T01:00:00+01:00

julia> ZonedDateTime(DateTime(2014,3,30,2), warsaw)
ERROR: DateTime 2014-03-30T02:00:00 does not exist within Europe/Warsaw

julia> ZonedDateTime(DateTime(2014,3,30,3), warsaw)
2014-03-30T03:00:00+02:00
``
```

**Comment by MichaelHatherly** [comment]
It was intentionally left undocumented :smile: since I'd not settled 100% on how things should be handled. Currently, https://github.com/JuliaDocs/Documenter.jl/blob/dba8811e84fcc6fce48d38bebfe3cdf19d223d8a/src/DocChecks.jl#L185-L189, we use `[...]` to signify ignored output.

I'm very open to other solutions though. Having to deal with changing file and line numbers is something I'd really like to avoid, not sure the best way though.

**Comment by omus** [comment]
I think that the writer of the documentation needs to include the exception (like how things currently work) but there should be an option to render the current stack trace. Part of this option could allow you to limit how many lines of the stack trace to display which would be followed by an ellipsis if it was truncated.

**Comment by MichaelHatherly** [comment]
Sounds reasonable to me. Might be best to add without an option initially and see how useful that is first, I've generally been trying to avoid adding too many options.

**Comment by omus** [comment]
Agreed. If such an option existed I think it would default to showing zero lines from the stack trace.

**Comment by MichaelHatherly** [comment]
So something like

```
``@doctest
julia> div(1, 0)
ERROR: DivideError: integer division error
[...]
``
```

would pass tests and then render as

```
``jlcon
julia> div(1, 0)
ERROR: DivideError: integer division error
 in div(::Int64, ::Int64) at ./int.jl:115
 in eval(::Module, ::Any) at ./boot.jl:231
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
``
```

or whatever the trace happens to be.

**Comment by omus** [comment]
That makes sense to me. So what about:
```
``@doctest
julia> div(1, 0)
ERROR: DivideError: integer division error
``
```
would it pass the tests and render as:
```
``jlcon
julia> div(1, 0)
ERROR: DivideError: integer division error
``
```
I'm mostly curious to what the behaviour is if `[...]` is excluded.

**Comment by MichaelHatherly** [comment]
I suppose we could just leave out the `[...]` completely. Just have it match the generated error via `startswith`.

**Comment by MichaelHatherly** [comment]
That one would pass tests, but render with the backtrace included I'd think.

**Comment by MichaelHatherly** [comment]
Revisiting this I think the current approach taken is probably the least likely to cause issues since we don't do any rewritting of the printed stacktrace. Just matching the start of the expected error with the start of the actual error seems to work fine as far as I can tell. We can just leave it up to the doctest author whether they want to include the full trace or just the first few lines.

Marking this as a doc issue that just need some clarification probably.
