### ISSUE TITLE
debug messages for docs deployment

### ISSUE THREAD

**Issue by arturgower** [JuliaDocs/Documenter.jl#1122]
First, this is an amazing package.

I am trying to get better debug messages to understand why my docs will not deploy.

See my [travis.yml](https://github.com/arturgower/EffectiveWaves.jl/blob/8dc1239509a8eda6cdd65bb359997fd43e4afba5/.travis.yml), the [travis log file](https://travis-ci.org/arturgower/EffectiveWaves.jl/jobs/582178153), and [docs/make.jl](https://github.com/arturgower/EffectiveWaves.jl/blob/8dc1239509a8eda6cdd65bb359997fd43e4afba5/docs/make.jl). Even though I've set `DOCUMENTER_DEBUG=true` I do not see any more debugger info. How do I get better debug info?

**Comment by mortenpi** [comment]
I think you are running into these deprecations: https://github.com/JuliaDocs/Documenter.jl/blob/346274cb88d9528011b114732a39ab86beb0f48e/src/Documenter.jl#L534-L548

Not sure why the deprecation warnings did not show up.

**Comment by arturgower** [comment]
Yes you are absolutely right, problem solved, `deploydocs` can not contain the arguments `julia` or `osname`. 

I've now seen that several other packages have their docs deployment broken due to this, so getting the warnings working would be good.

**Comment by mortenpi** [comment]
Hmm, looking at it again, you already have one deprecation warning [here](https://travis-ci.org/arturgower/EffectiveWaves.jl/jobs/582178153#L393-L395). I don't know if it is a bug or a feature, but Julia seems to only print a single deprecation warning (per function?).

For our purposes, that's a bit suboptimal, so I think we should be using `@warn` instead of `Base.depwarn` in the future. These particular warnings, however, have been removed on master anyway.
