### ISSUE TITLE
Why is inlined code rendered in red?

### ISSUE THREAD

**Issue by jonathan-laurent** [JuliaDocs/Documenter.jl#1212]
I noticed that `Documenter.jl` renders inlined code in red (unless a hyperlink is attached, in which case it is rendered in blue). See [here](https://juliareinforcementlearning.org/ReinforcementLearning.jl/latest/components/environments/) for an example.

I find this choice questionable and I am wondering how it is motivated. Indeed, the color red is more conventionally used to attract one's attention on a malformed element (such as a broken hyperlink) or to make an element strongly  stand-out. To me, rendering inlined code in black or gray would be more readable and less confusing.

Does anyone have thoughts on this?

**Comment by KristofferC** [comment]
I do think that the current red pulls a bit too much attention to the random inline quoted code. It is also quite unfortunate that you can no longer see when quoted code is a link. Personally, I would prefer putting it back the way it was.

**Comment by mortenpi** [comment]
Fair enough. I actually do agree that if there is a lot of inline code in a paragraph, the red is jarring. As to the "why", just for the record, it's the Bulma default for inline code.

My current intention is to set the inline code color to `#000`, which creates a bit more contrast than the color of the main text. I do think it's good if the inline code stands out slightly. But I am not 100% sure what to do in the dark theme yet.

> It is also quite unfortunate that you can no longer see when quoted code is a link.

Do you have an example of that? This was fixed in #1167 and included in the 0.24.0 release.

**Comment by KristofferC** [comment]
> Do you have an example of that? 

On e.g. https://kristofferc.github.io/PackageCompilerX.jl/dev/sysimages/#Creating-a-sysimage-using-PackageCompilerX-1 I see

![bild](https://user-images.githubusercontent.com/1282691/70826064-4ecd9180-1de6-11ea-9be9-38e3f753485f.png)

but `create_sysimage` is a link while the others are not.

But maybe my Documenter version got out of date (https://github.com/KristofferC/PackageCompilerX.jl/blob/6edc13fd4e7c0547351785958cc6b2f701c19373/docs/Manifest.toml#L26). I will try update it.
