### ISSUE TITLE
`push_preview` does not work in Github Actions

### ISSUE THREAD

**Issue by asinghvi17** [JuliaDocs/Documenter.jl#1230]
With `deploydocs(..., push_preview = true)`, I get this output in the log:
```julia
┌ Info: Deployment criteria for deploying devbranch build from GitHub Actions:
│ - ✔ ENV["GITHUB_REPOSITORY"]="JuliaPlots/MakieGallery.jl" occurs in repo="github.com/JuliaPlots/MakieGallery.jl"
│ - ✔ ENV["GITHUB_EVENT_NAME"]="push" is "push"
│ - ✘ ENV["GITHUB_REF"] matches devbranch="master"
│ - ✔ ENV["GITHUB_ACTOR"] exists
│ - ✔ ENV["DOCUMENTER_KEY"] exists exists
└ Deploying: ✘
```
https://github.com/JuliaPlots/MakieGallery.jl/pull/187/checks?check_run_id=411479592

The `make.jl` file is here: https://github.com/JuliaPlots/MakieGallery.jl/blob/master/docs/make.jl

**Comment by mortenpi** [comment]
The issue is that your [documentation build runs `on: push` not on `on: pull_request`](https://github.com/JuliaPlots/MakieGallery.jl/blob/master/.github/workflows/documentation.yml#L3). Hence the `GITHUB_EVENT_NAME` is set to probably `push`, whereas Documenter expects `pull_request`.

For the PR previews to work, you need to make sure that your builds run as part of the PR (i.e. `on: pull_request`).
