### ISSUE TITLE
Including documented fields for custom type

### ISSUE THREAD

**Issue by tribut** [JuliaDocs/Documenter.jl#126]
If I follow the [Julia documentation](http://docs.julialang.org/en/release-0.4/manual/documentation/#types) on documenting types, that is I write

~~~~
"""
    MyType

A thing that does something.
"""
type MyType
    "A very important field"
    x
    "Another field"
    y
end
~~~~

is there a way to include the documentation on the fields in the output generated by Documenter?

**Comment by MichaelHatherly** [comment]
At the moment there isn't a way to do that. Once `0.5` is released I'll be implementing this kind of auto-generated context-dependant content in a separate package so that the output can also be viewed in the REPL and not just in Documenter's generated output.

The current idea is to use something like the following syntax:

```julia
"""
    MyType

A thing that does something.

$__FIELDS__
"""
type MyType
    "A very important field"
    x
    "Another field"
    y
end
```

Which will generate a docstring that looks something like

```markdown
    MyType

A thing that does something.

# Fields

- `x`: A very important field
- `y`: Another field
```

Other "magic" variables similar to `__FIELDS__` might include `__SIGNATURE__`, `__METHODS__`, and whatever else we can come up with.

This isn't really actionable within Documenter in a very general way (though we could come up with a hacky workaround), so I'll close this for now and comment here once I get around to actually implementing it.

**Comment by tribut** [comment]
Thanks a lot for the answer.

**Comment by iamed2** [comment]
Reopen?

**Comment by mortenpi** [comment]
No need, we have https://github.com/JuliaDocs/DocStringExtensions.jl

**Comment by iamed2** [comment]
Oh cool, thanks!
