### ISSUE TITLE
Documentation ordering

### ISSUE THREAD

**Issue by hayd** [JuliaDocs/Documenter.jl#13]
At the moment, all the md files are built and dumped into build.

If using mkdocs (#10) these have to be specified in the yaml. One could do the same in a top level latex file to input these and add style. This seems like a duplication of effort (specifying the ordering).

I would propose, either:

1. mkdocs.yml pages-section is required, use this to decide the ordering and naming of sections. Warn/error if sections are missing in both src or yaml. Use this for generating single-page html/latex.
2. makedocs function allows passing of this ordering (as title => filename pairs). Warn/error if sections missing or do not exist in both src or yaml.

My preference is the mkdocs.yml as this already exists, and allows nested files etc.

This is crucial in compiling to a single document (e.g. #4).

**Comment by MichaelHatherly** [comment]
I don't mine either option really. Go with the `mkdocs.yml` and we can see how it works out in practise.

**Comment by MichaelHatherly** [comment]
Specifying page order was added in https://github.com/JuliaDocs/Documenter.jl/commit/e7de65974efcbeadbadc16e40feec2f1d8aa14ad (currently internal and undocumented since markdown output doesn't really need it). Closing this issue since https://github.com/JuliaDocs/Documenter.jl/issues/100 supersedes this I think.
