### ISSUE TITLE
Respect users' preference for light/dark mode

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#1320]
Coming soon (or even already here) to a browser near you, a way of choosing to display light or dark mode:

https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme

Is this something that can be added to Documenter?

**Comment by mortenpi** [comment]
Documenter's theme switching is JS-based, but that shouldn't be a problem, since it seems that you can [access that media feature via JS](https://web.dev/prefers-color-scheme/#loading-strategy) too. Would probably be a rather simple modification to [`themeswap.js`](https://github.com/JuliaDocs/Documenter.jl/blob/master/assets/html/themeswap.js).
