### ISSUE TITLE
Valid DOI redirected links trigger warnings.

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaDocs/Documenter.jl#1344]
I'm seeing lots of doc warnings regarding redirected DOI links. For example

```
┌ Warning: linkcheck 'https://doi.org/10.1016/0169-8095%2894%2900090-Z' status: 302, redirects to https://linkinghub.elsevier.com/retrieve/pii/016980959400090Z.
└ @ Documenter.DocChecks ~/.julia/packages/Documenter/PLD7m/src/DocChecks.jl:223
```

Both the [first](https://doi.org/10.1016/0169-8095%2894%2900090-Z) and [second](https://linkinghub.elsevier.com/retrieve/pii/016980959400090Z) links work. It doesn't seem like this should be a warning.

**Comment by simonbyrne** [comment]
It's especially confusing since in this case since they trigger an `@warn`, but don't actually cause a `linkcheck` failure:
https://github.com/JuliaDocs/Documenter.jl/blob/8e53b7b8de30ed342ef919f6b351b56a6cc75482/src/DocChecks.jl#L222-L226
whereas other errors that _do_ trigger linkcheck failures sometimes trigger an `@warn`:
https://github.com/JuliaDocs/Documenter.jl/blob/8e53b7b8de30ed342ef919f6b351b56a6cc75482/src/DocChecks.jl#L236-L237
and sometimes an error:
https://github.com/JuliaDocs/Documenter.jl/blob/8e53b7b8de30ed342ef919f6b351b56a6cc75482/src/DocChecks.jl#L232-L233

Would it be possible to make them so that any linkcheck failures always trigger an `@error`?

**Comment by simonbyrne** [comment]
In this specific case, I don't think 302 errors should trigger a warning, since it is meant to be used as a temporary redirect:
https://en.wikipedia.org/wiki/HTTP_302

**Comment by mortenpi** [comment]
> Would it be possible to make them so that any linkcheck failures always trigger an `@error`?

An argument one could make is that e.g. with 301 redirects the links are still technically working, so we shouldn't error on them.

**Comment by simonbyrne** [comment]
I meant any failure which does `push!(doc.internal.errors, :linkcheck)`

**Comment by charleskawczynski** [comment]
> An argument one could make is that e.g. with 301 redirects the links are still technically working, so we shouldn't error on them.

But is warning the best option? Can’t we check the redirected link and warn/error if it’s broken and pass otherwise? @mortenpi

**Comment by mortenpi** [comment]
> Can’t we check the redirected link and warn/error if it’s broken and pass otherwise?

That's an additional step, that we actually follow the 3XX redirects. We could definitely do that if someone wants to take a stab at implementing this.

**Comment by charleskawczynski** [comment]
Ok. Should we reopen this issue, then?

**Comment by mortenpi** [comment]
Perhaps a new one? The DOI/302 issue has been resolved (temporary redirects do not print a warning nor an error).
