### ISSUE TITLE
add example to @docs for type & multiple constructors 

### ISSUE THREAD

**Issue by tpapp** [JuliaDocs/Documenter.jl#1361]
I am thinking of making a PR to the docs, adding an example documenting constructors & types, and I am asking to check first. In

```julia
"what a splendid type"
struct Foo{T,S} end

"0"
Foo() = Foo{Nothing,Nothing}()

"1"
Foo{T}() where T = Foo{T,Nothing}()
```

I think that

````
```@docs
Foo        # what a splendid type
Foo()      # 0
Foo{T}()   # 1
Foo{T,S}() # undocumented
```
````

is the recommended way to get everything, is this correct?

**Comment by mortenpi** [comment]
Oops, sorry, this slipped through the cracks. The block you have looks good, it's what how I would expect it to work. Whether it actually works is a separate question, since there may be bugs in both Documenter and Julia docsystem.

But trying it out and documenting how to do this properly would be good I think. A working example could also be added to the [Showcase page](https://juliadocs.github.io/Documenter.jl/stable/showcase/#Docstrings).

**Comment by tpapp** [comment]
Thanks, I will do that.
