### ISSUE TITLE
Include files generated by examples in deployment

### ISSUE THREAD

**Issue by bbejanov** [JuliaDocs/Documenter.jl#1404]
If a PNG file is not part of the repo but is generated by a ` ```@repl ``` `  block, it doesn't get included in the deployment to gh-pages.

**Comment by mortenpi** [comment]
They should. The `pwd` for the at-repl block is in the `build/` directory, all of which gets deployed. Without additional information, it's hard to tell what's going on -- is it a public package? There _may_ be an issue with linking to those files e.g. with `![]()`, because of the directory structure `HTMLWriter` creates, but the file should definitely exist on the `gh-pages` branch.

**Comment by bbejanov** [comment]
Thanks for your reply. The problem I had was that the two png images at https://bankofcanada.github.io/DocsEcon.jl/dev/Tutorials/US_SW07/main/ were not showing up. I worked around by adding the png files to the repo. Now I removed the two png files to try again, but the problem is not there anymore. The images are showing correctly now. I'm not able to replicate the issue. I'm sorry about that. Thanks again for your help!
