### ISSUE TITLE
font choice makes \prime look like a single quote

### ISSUE THREAD

**Issue by shishini** [JuliaDocs/Documenter.jl#1408]
On this [page](https://docs.julialang.org/en/v1/manual/variables-and-scoping/), there is a function sum_to′ (last character is \prime) 
the font choice make look like sum_to' 

single quotes are not allowed in function names, and this can create a confusing situation for beginners

**Comment by mortenpi** [comment]
To be more specific, the issue is that Roboto Mono (Documenter's monospace font) renders `\prime` i.e. `′` ([U+2032](https://unicode-table.com/en/2032/)) like an apostrophe `'` ([U+0027](https://unicode-table.com/en/0027/)). The best option would be to see if that could fixed in the font.

However, I think the better idea is to discourage the use of `\prime`. Even if Documenter would render them distinctly, I think it's bound to cause confusion, as many (if not most) fonts will render them either identically or in a way that makes it hard to distinguish.

X-ref: JuliaLang/julia#37173

**Comment by fredrikekre** [comment]
Not an issue with JuliaMono.
