### ISSUE TITLE
pdf can't be created from the compiled .tex file

### ISSUE THREAD

**Issue by DrKrar** [JuliaDocs/Documenter.jl#1418]
![Screenshot 2020-09-19 221904](https://user-images.githubusercontent.com/1588708/93688434-2f2a6e80-fac6-11ea-9f66-56ae668aabb0.png)

**Comment by originalsouth** [comment]
Can you please post the full error report?
Probably latex is not (properly) installed.

**Comment by mortenpi** [comment]
If it is the LaTeX installation, you can always try switching to the Docker image on Travis: https://juliadocs.github.io/Documenter.jl/dev/man/other-formats/#Compiling-using-docker-image

It's also possible that we're generating bad TeX, which makes `latexmk` exit with an error code, but we'd need an MWE for that. A way to debug that is to set the `DOCUMENTER_LATEX_DEBUG` environment variable to an empty string so that Documenter would copy the TeX files under `docs/` (e.g. by calling `DOCUMENTER_LATEX_DEBUG= julia --project=docs/ make.jl`). Then you can invoke latexmk outside of Documenter, which should significantly aid debugging.

**Comment by mortenpi** [comment]
Closing this since there is nothing actionable here. X-ref #1697 for better access to LaTeX logs.
