### ISSUE TITLE
Documenter for Julia manual

### ISSUE THREAD

**Issue by omus** [JuliaDocs/Documenter.jl#142]
Are there plans to use Documenter.jl for the Julia manual? If so, we should make a milestone for that goal and try to identify what is needed to be done. I'm definitely willing to help out.

**Comment by MichaelHatherly** [comment]
Yes, the current plan is use Documenter for `Base` as well &mdash; no point having two different systems any more if we can avoid it. There currently https://github.com/JuliaLang/julia/issues/12573 open, as mentioned there I'm not going to push for this to get done for `0.5` since that's much too soon now.

I'm currently working on a script to automatically convert the whole manual to markdown in one pass. So far it seems to be working out fine and I'll probably push the results to a `JuliaDocs` repo within the next week. Help would definitely be much appreciated at that point so that we can be 100% sure it's a lossless conversion before opening a PR in base.

As I also mentioned in 12573, we're planning to use the HTML rendering that @mortenpi is currently working on (GSoC) instead of the markdown/mkdocs approach currently being used by packages.

There's also #110 and #109 that probably should be resolved before merging anything into base.

**Comment by MichaelHatherly** [comment]
An initial draft of the conversion is now available at https://github.com/MichaelHatherly/julia-docs. Not tried to run Documenter on it yet though. @mortenpi feel free to use it as "test data" for your work. Any problems with the conversion can be opened as issues in that repo if you notice them.

**Comment by mortenpi** [comment]
> An initial draft of the conversion is now available at https://github.com/MichaelHatherly/julia-docs.

Awesome! I shoehorned this into my [Documenter doc HTML build](http://mortenpi.eu/documenter-html/manual/arrays.html), it's the bottom three sections.

I had to hack around a few issues in Documenter to get it working like this, but I basically didn't see any issues with the conversion itself. I haven't checked the output that thoroughly, and there definitely were some `DocsNodes` that failed etc., but I don't know why at the moment.

**Comment by MichaelHatherly** [comment]
> I shoehorned this into my Documenter doc HTML build, it's the bottom three sections.

I'm surprised that came out as well as it did, wasn't expecting it to work at all.

Regarding `DocsNode` failures, that's probably something to do with all the duplicate signatures in the `@docs` blocks. Also might need some `CurrentModule = ...` scattered around for good measure as well.

**Comment by mortenpi** [comment]
I think this can be closed now (JuliaLang/julia#18588).
