### ISSUE TITLE
Coverage reports of Documenter.jl's tests have not been sent

### ISSUE THREAD

**Issue by kimikage** [JuliaDocs/Documenter.jl#1459]
It doesn't seem to have been updated for a long time, is this intentional?

https://github.com/JuliaDocs/Documenter.jl/blob/d06fa07e047e84ed63b58290e0c5d0c0fb3b8944/.travis.yml#L21-L24

Shall we split up some execution environments or jobs (e.g. nightly, theme) into GitHub Actions?

**Comment by mortenpi** [comment]
Nope, definitely not intentional: #1460.

> Shall we split up some execution environments or jobs (e.g. nightly, theme) into GitHub Actions?

I am not actually sure what the ecosystem is doing nowadays in this respect, but I feel that the go-to CI should probably be GitHub Actions nowadays, since it integrates better? With that in mind, it might make sense to move CI over to it. It just hasn't really been a priority, since Travis works just fine.

We could still keep Travis around as well, just to make sure that everything runs fine there too.

In any case, the theme check would be a good fit for a separate GA workflow.
