### ISSUE TITLE
Double back-tick `` is a crazy replacement for $

### ISSUE THREAD

**Issue by ViktorQvarfordt** [JuliaDocs/Documenter.jl#146]
I've heard that Documenter.jl is planning on using double back-ticks to enclose inline LaTeX math, instead of the standard; enclosing inline math in dollar signs. Using double back-ticks is crazy! It deviates from the LaTeX convention. I promise that everyone will be confused if this is implemented. It must be stopped.

One might counter with that `$` are already used for string interpolation. This is not a reason for going crazy. All we need is some sort of raw strings. I've heard that https://github.com/stevengj/LaTeXStrings.jl does something like this. Even something as simple as the following works, so this argument seems void.

```julia
macro raw_str(str) str end
raw"There is no $interpolation in here!"
```

(Personally I'd prefer to see single quotes `'` for raw strings and double quotes `"` for fancy interpolating strings. This would break the syntax for chars, but who uses chars? Give them some other syntax, perhaps `char"a"` or `c"a"`.)

**Comment by MichaelHatherly** [comment]
> I've heard that Documenter.jl is planning on using double back-ticks to enclose inline LaTeX math

Upstream issue, not specific to Documenter.

> It deviates from the LaTeX convention.

The LaTeX syntax is `\(...\)`. `$...$` is standard in plain TeX.

> I promise that everyone will be confused if this is implemented. It must be stopped.

Making blanket statements about how other people will react to something isn't all that helpful. It may have confused you, but that does not mean everyone will have the same experience.

> One might counter with that `$` are already used for string interpolation.

Reusing the same character for completely different purposes (interpolation and math in this case) is, from my experience with new docstring writers, more confusing than using a distinct syntax for each. The `$` syntax for interpolation isn't going away, so math syntax has to fit in around it rather than the other way around.

> Even something as simple as the following works, so this argument seems void.

I'm aware of that. `@doc_str` is already implemented in `Base` if you really need to avoid escaping characters, though it should be avoided wherever possible since it does not preserve all the raw information associated with the docstring it is applied to.

Additionally, using non-standard string literals such as `@raw_str` or `@doc_str` does not allow for any form of interpolation. Interpolation is particularly useful in docstrings where one would like to automatically keep documentation up-to-date with data available outside of the docstrings.

> This would break the syntax for chars, but who uses chars?

Not sure if you are serious with this suggestion? Char literals are used in many places and would be a very disruptive change at this point. (This char syntax suggestion is an upstream issue. Please open an issue in the main Julia repo if you want to discuss changes like that.)

**Comment by mortenpi** [comment]
> > I've heard that Documenter.jl is planning on using double back-ticks to enclose inline LaTeX math

> Upstream issue, not specific to Documenter.

Has there actually been any (upstream) discussion about this?

**Comment by MichaelHatherly** [comment]
> Has there actually been any (upstream) discussion about this?

The double backtick syntax has been around for a long while now on `master` &mdash; since mid-December. [GitHub search]( https://github.com/JuliaLang/julia/search?q=backtick+latex&type=Issues&utf8=%E2%9C%93) is simplest way to find out the history. Also, since `git` preserves the repo history you can also search through that as well.

**Comment by mortenpi** [comment]
I was mainly wondering if there has been any recent discussion, since I couldn't find any issues/PRs that would've made any decisions. And, as far as I can tell, the `$` syntax is still supported in 0.5, and the backtick provides an alternative to that to get around string interpolation issues (?). Are there any plans to deprecate the `$` syntax in "JuliaMark"?

**Comment by MichaelHatherly** [comment]
> Are there any plans to deprecate the `$` syntax in "JuliaMark"?

Once I (or someone else) eventually gets round to doing https://github.com/JuliaLang/julia/issues/12740 then perhaps, but it may be possible to just leave `$` as is if people really want to use it instead, but document the preferred backtick syntax.

**Comment by mortenpi** [comment]
> document the preferred backtick syntax

I missed this before, but the manual already recommends double backticks for equations in docstrings ([docs.julialang.org:Documentation, item 6](http://docs.julialang.org/en/latest/manual/documentation/)).

**Comment by MichaelHatherly** [comment]
>  the manual already recommends double backticks

Ah, yes, forgot it was already in there.

**Comment by ViktorQvarfordt** [comment]
Sorry if I did not sound so serious, but I thought double backticks were not so serious.

The problem I see is that Julia is largely geared toward the scientific community, a community that frequently use LaTeX and likes adhering to standards. If Julia starts reinventing wheels it may not be received as well as it could.

If introducing a way to modify the interpolation is not appreciated, I would much rather see escaped dollar signs than double backticks. This fits directly with how strings currently works, without inventing new syntax. Also, note that these have the same number of characters.

**Comment by MichaelHatherly** [comment]
> I would much rather see escaped dollar signs than double backticks.

You're more than welcome to continue using dollar signs and escaping them or use `@doc_str`. As I mentioned above that syntax probably won't go away in the short-term or probably ever, so if you prefer that syntax then you can continue using it. The markdown parser it's forcing you one way or the other here.

> If Julia starts reinventing wheels it may not be received as well as it could.

The syntax isn't completely made up, and was based on http://scholarlymarkdown.com syntax. (Yes, that project does appear to have been very quiet for a while, but that doesn't mean decent ideas can't be borrowed.)

> Also, note that these have the same number of characters.

Yes, same number of characters when reading it, but that's not always a great measure for ease of typing. A double backtick will, I believe, always be easier to type than `\$`.

**Comment by ViktorQvarfordt** [comment]
I'ts not that I think that dollar signs are better than backticks, I have lots of complaints on the latex syntax. The point is rather that if we want to write latex (which we do), it would be nice to actually use the syntax of latex. (To claim that the latex syntax is `\(...\)` and not `$...$` is not really fair, the dollar signs are not deprecated. However, the double dollar signs `$$...$$` are deprecated in favor of `\[...\]`.) 

However, I've been thinking about this some more, and I've come to the conclusion that since a lot of specific syntax/formatting assumptions are already being made for the docstrings, i.e. being typeset using markdown, it is not that big of a deal to introduce the double backtick syntax, which actually fits well into the conventional markdown syntax. It's unfortunate that it's non-standard, but hopefully this will catch on.

Anyhow, escaping dollar is not the big annoyance, it is all the backslashes that must be escaped when writing latex in a string, suggesting the need of some sort of raw string, and how raw strings can be used as docstrings. I tried to use the  `raw_str` macro on a string above a function, Julia did not recognize that, the function did not get documented, and no error or warning was thrown.

**Comment by MichaelHatherly** [comment]
> To claim that the latex syntax is `\(...\)` and not `$...$` is not really fair, the dollar signs are not deprecated.

Yes, I always forget it's only the double `$` that's actually deprecated not single `$` as well.

> It's unfortunate that it's non-standard, but hopefully this will catch on.

Perhaps it will catch on. The nice thing about it is that in markdown parsers that don't support it, it'll just get parsed as a code literal rather than potentially messing up surrounding markdown syntax since the contents of `$...$` or `\(...\)` may get parsed as some markdown syntax.

>  it is all the backslashes that must be escaped when writing latex in a string

Agreed, definitely. I've been wondering how best to resolve that part of it for a while now. One possible approach is with an interpolated non-standard string literal like `@raw_str` inside a docstring. (Another might be to used a char other than `\` and let the markdown parser convert it to `\`, though that might be going a little *too* far I think.)

> I tried to use the raw_str macro on a string above a function, Julia did not recognize that, the function did not get documented, and no error or warning was thrown.

Only plain strings (single double and triple double) and `@doc_str` are recognised as docstrings when placed above a toplevel definition. Initially the parser did just accept any non-standard string literal above, but that got changed shortly afterwards since it broke several packages.
