### ISSUE TITLE
Increase prominence of rendered DocsNode header

### ISSUE THREAD

**Issue by RalphAS** [JuliaDocs/Documenter.jl#147]
Presently the DocsNode headers are buried in context; with readthedocs theme they are actually smaller than the list headers in the associated docstrings.  Using an HTML header style (as in #25) could ameliorate this, but has the problem that it assumes too much about the document structure.  I suggest producing something like this:

``` html
<span class="docsnode">
<a id='MyModule.MyType' href='#MyModule.MyType'>#</a>
<span class="nodename">MyModule.MyType</span> &mdash;
<span class="nodeclass">Type</span>.</span>
```

Then presentation can be customized in CSS; for example:

```
.docsnode {
    font-size: 120%;
}

.nodename {
    font-weight: bold;
}

.nodeclass {
    font-style: italic;
}
```

**Comment by MichaelHatherly** [comment]
Sounds reasonable to me. I've been trying to avoid adding *too* much HTML to the markdown files that Documenter generates, but that seems pretty minimal to me. I'm happy to take a PR for this, otherwise I'll get around to adding it sometime later this week hopefully.

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing because a lot of the HTML has changed since 2016. Things look okay to me

![image](https://github.com/JuliaDocs/Documenter.jl/assets/8177701/90cff5a4-a101-4a23-8555-3e026397bc1d)
