### ISSUE TITLE
Wrong docstring displayed for overloaded functions

### ISSUE THREAD

**Issue by biona001** [JuliaDocs/Documenter.jl#1502]
In my package, I defined a [fit](https://github.com/OpenMendel/MendelIHT.jl/blob/master/src/fit.jl#L31) function but I also import the fit function used in `GLM.jl`.

But [my documentation](https://openmendel.github.io/MendelIHT.jl/latest/man/api/#StatsBase.fit) for `fit` only displays the docstring for `StatsBase.jl`. In my markdown file I tried many different ways which all doesn't work:
```
"""@docs       (don't know how to escape triple backticks)
  fit
  MendelIHT.fit
  fit(AbstractVector, AbstractMatrix, AbstractVecOrMat)
"""
```
How do I display *only* my `fit` and not other `fit`s defined in packages I use?

**Comment by MichaelHatherly** [comment]
Maybe try with `::`?

```
fit(::AbstractVector, ::AbstractMatrix, ::AbstractVecOrMat)
```

If that doesn't do it then it may has something to do with documenting a function from a different package (`StatsBase.fit`) for arguments that the `MendelIHT` package doesn't own.

**Comment by biona001** [comment]
Thank you for the suggestion. 

I just tried `fit(::AbstractVector, ::AbstractMatrix, ::AbstractVecOrMat)` and `fit(y::AbstractVector, x::AbstractMatrix, z::AbstractVecOrMat)`, but both times I get a Missing docstring warning:
```
┌ Warning: no docs found for 'fit(::AbstractVector, ::AbstractMatrix, ::AbstractVecOrMat)' in `@docs` block in src/man/api.md:20-22
│ ```@docs
│   fit(::AbstractVector, ::AbstractMatrix, ::AbstractVecOrMat)
│ ```
└ @ Documenter.Expanders ~/.julia/packages/Documenter/FuXcO/src/Expanders.jl:334
```
I also tried renaming `fit` to a non-imported function name `fit_iht`, which everything just works. I suppose I could do this for the time being. 

Some googling revealed issue #1169, which might be related to this...

**Comment by knuesel** [comment]
@biona001 : you don't actually define a new `fit` function: instead, you extend `GLM.fit` with a new method (to define a new `fit` function, do `using GLM: fit` instead of `import GLM: fit`). And GLM also doesn't define `fit` but extends the function from `StatsBase`.

Then it makes no difference if you write `fit` or `MendelIHT.fit` in the `@docs` block: it always refers to the same Julia object:

```julia
julia> using GLM, MendelIHT, StatsBase

julia> GLM.fit === MendelIHT.fit === StatsBase.fit
true
```

Maybe that's what you want, so users can write `fit` without prefix to use GLM methods or your method depending on the arguments, and it puts your documentation together with the other methods when typing `?fit` in the REPL.

To make it work in Documenter, you can specify this particular method in the `@docs` block: in the source file,  the docstring is attached to the following declaration:

```julia
function fit(
    y         :: AbstractVector{T},
    x         :: AbstractMatrix{T},
    z         :: AbstractVecOrMat{T};
    ...
    ) where T <: Union{Float64,Float32}
```

So the `@docs` block should contain the line `fit(::AbstractVector{T}, ::AbstractMatrix{T}, ::AbstractVecOrMat{T}) where T <: Union{Float64,Float32}`.

Another solution is to simply write `fit` in the `@docs` block, but add `modules = [MendelIHT]` in `make.jl` to [keep only methods from your module](https://juliadocs.github.io/Documenter.jl/stable/man/guide/#Filtering-included-docstrings).

However I think in this case extending `GLM.fit` is type piracy (you don't own the types in your `fit` signature) so it's probably best to make your own function.

**Comment by biona001** [comment]
I see. Thank you for the suggestion. It's good to know defining my own function `fit_iht` is even better (more Julian?) than extending `fit` from GLM.
