### ISSUE TITLE
Modernise tests

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaDocs/Documenter.jl#154]
We should switch over to using `@testset` at some point.

**Comment by mortenpi** [comment]
I was experimenting with `@testset` a bit and I came across a few small things:

* v0.4 doesn't have `@testset`s and [BaseTestNext.jl](https://github.com/JuliaCI/BaseTestNext.jl) should be used. Should we drop that into `test/REQUIRE`, even though it will then get installed on 0.5 as well (but not used because of in-code version checks)?

* Modules can't be defined within a `@testset` (not the top-level), but we use them quite extensively (testsets within a module are fine, of course). Basically, the question is how should we group our tests? I would seem convenient to have one master `@testset`, but that would be problematic because of that. Should we just have multiple "top-level" testsets, corresponding, I guess, to the top-level modules that we have?

Also, while we're at it, should we perhaps split `test/runtests.jl` into multiple files as well? The tests are a bit hard to read at the moment.

**Comment by MichaelHatherly** [comment]
> Should we drop that into `test/REQUIRE`


Yes, no calls to `Pkg.add` within `runtests.jl`.

>  Basically, the question is how should we group our tests

Have `runtests.jl` wrap a bunch of `include`s that each contain the test modules and their inner `@testset`s? Not sure if that works though.

Just one toplevel testset if possible.

Yes, `runtests.jl` needs splitting. It's really just grown organically as needed until now. Definitely getting a bit big.

**Comment by mortenpi** [comment]
Should this have a 0.4 milestone as well?

**Comment by MichaelHatherly** [comment]
Yup, `0.4` sounds good to me.
