### ISSUE TITLE
Switch off ligatures by default?

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#1610]
People have surprisingly strong opinions about fonts, especially when it comes to things like contextual and stylistic alternates (aka ligatures) in monospaced fonts.

Leaving aside personal taste, I'd suggest that in documentation their presence might need explanation, since it might not be easily apparent to everyone that what looks like an arrow  `→` is actually formed by typing `-` and `>`. 

I wonder whether it would be better to have them switched off by default, for documents such as the Julia manual, but have them able to be switched on for documents where basic Julia knowledge is assumed.

**Comment by fredrikekre** [comment]
Would be good to at least document how to turn it off (as for the Julia manual). Of course, I would prefer making that default and document how to turn it on instead.

**Comment by KristofferC** [comment]
I also think that default to ligatures of makes sense.

**Comment by cormullion** [comment]
Is there an easy way to inject CSS into the provided themes? I used to have to edit them manually to make tweaks, which was a bit of a nuisance. The Julia manual had a handy CSS file, but is there similar for Documenter?

**Comment by mortenpi** [comment]
I did not realize that JuliaMono uses ligatures. I strongly agree that they should not be enabled by default (#1617).

I also do not think that manuals should really use them at all by default -- most people who read a manual of any package are likely not familiar with ligatures. For that reason I don't necessarily think it is a bad thing if we do not let manual authors enable them easily.

I would not mind a per-user option (e.g. another toggle next to the theme one), but I am not sure how much use it would get (mostly because you'd have to enable it for each package separately).
