### ISSUE TITLE
Building a stable and latest release

### ISSUE THREAD

**Issue by pkofod** [JuliaDocs/Documenter.jl#183]
So, over at Optim.jl we currently have the first master with Documenter. This means that there is no tagged version with Documenter docs, so while http://www.juliaopt.org/Optim.jl/latest/ works, http://www.juliaopt.org/Optim.jl/stable/ does not. Is it correct that if I add a badge for the stable to our readme, and tag a version, then Documenter will build both a stable and latest version, and then the stable link (badge) will work when Documenter has run? I just want to make sure that the README distributed with the new version has links that work.

**Comment by MichaelHatherly** [comment]
Yes, that should work fine.

**Comment by pkofod** [comment]
Perfect, thanks! I'm very exited to finally make the switch "official".

**Comment by pkofod** [comment]
Reopening this, as it didn't build the stable version, but I don't think it did the latest either.

I've added the debug key, and I get the following on linux+julia v0.5 which should be the deploy combination: https://travis-ci.org/JuliaOpt/Optim.jl/jobs/152024164

Any idea why?

**Comment by MichaelHatherly** [comment]
By default `deploydocs` will deploy from the `nightly` buildbot. Since the `.travis.yml` file only has `0.4` and `0.5` (https://github.com/JuliaOpt/Optim.jl/blob/276c98d3a61432a14fad388debce91d056653b88/.travis.yml#L6-L7) it won't build. Add `julia = "0.5"` to the `deploydocs` call like so:

```julia
deploydocs(
    repo = "github.com/JuliaOpt/Optim.jl.git",
    julia = "0.5",
)
```

and that should start building properly I think.

**Comment by pkofod** [comment]
That does makes sense as we are in one of those lovely transitioning periods between versions :) Thanks for the quick help. I'll see if it works and report back.

**Comment by MichaelHatherly** [comment]
:+1: no prob.

**Comment by pkofod** [comment]
So it did work. Perfect. Now I just need to return to the original question :) Do I need to do something to get a stable and a latest version? It doesn't seem to deploy to http://www.juliaopt.org/Optim.jl/stable

**Comment by MichaelHatherly** [comment]
`stable` (and `v0.6.0` etc.) folders only get built when a new tag is pushed. Since you've already pushed a `v0.6.0` tag prior to fixing the `julia = "0.5"` problem Documenter won't be able to build a `stable` version until you tag a new version.

To get around that you could, if `master` and tag `v0.6.0` are similar enough(?), just copy the `latest` folder to new `stable` and `v0.6.0` folders on the `gh-pages` branch and push those changes manually.

**Comment by pkofod** [comment]
Of course. I will do that. I *just* tagged v0.6.0, so latest and master are identical :)

**Comment by pkofod** [comment]
Re-closing as it works, thanks!
