### ISSUE TITLE
RFC: Drop support for Julia 1.0-1.5

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#1835]
So only support Julia 1.6+ from 0.28 onwards. Curious to know if there are any objections.

We don't really need <= 1.5 support for Julia docs themselves. For packages, you don't need to be able to run Documenter with every supported Julia version, and you can just build docs with Julia 1.6+. On the other hand, it would allow us to use JLLs etc. freely here (e.g. for Git, which is what prompted this).

If anyone really has a package that is only being run on Julia <= 1.5 (maybe privately), then they can still keep using the 0.27 branch.

**Comment by odow** [comment]
No objections. No one should be using 1.1--1.5. They should either be using 1.0 or 1.6, and since 1.6 is now the LTS, they should move from 1.0 to 1.6 which is a non-breaking change. Even then, they can keep using 1.0 and Documenter 0.27, so there's no harm.

JuMP dropped <1.6 support when we release 1.0 and there hasn't been any issues. It really simplified our binary dependency story.
