### ISSUE TITLE
Make "Extended help" sections in docstrings collapsible

### ISSUE THREAD

**Issue by halleysfifthinc** [JuliaDocs/Documenter.jl#1852]
An "Extended Help" section can be added to docstrings that is only shown in the REPL help mode with an extra prefixed `?`, e.g. `??foo` from the default repl, or `?foo` when already in help mode.

I think a similar hidden-by-default behavior would be appropriate for producing the docs from docstrings. Could the "Extended Help" section in docstrings be automatically wrapped in a `<details><summary>Extended help</summary>... extended help contents ...</details`?

**Comment by mortenpi** [comment]
I am not really sure I see the advantage in having the docstrings collapsed in the HTML docs, so I am not entirely sure we want this.

Where I might see some value here is perhaps together with #1079, so that when you include the same docstring again somewhere else, it would only show the short version.

**Comment by halleysfifthinc** [comment]
In case I wasn't clear, I'm only requesting that the "Extended help" section be in a collapsible/collapsed by default section. This would match the intent and behavior of extended help in the REPL, where the complete docstring might be particularly long and  further examples and/or information that won't be relevant for most people (e.g. implementation details, interface definition, etc.) are only shown when requested.

If this feature isn't wanted in Documenter, do you have any pointers as to how/what I could modify to enable this for my own package documentation?

**Comment by mortenpi** [comment]
I just feel that there isn't much value in hiding parts of the docstrings in the HTML docs, and could even be counterproductive (forcing people to make an extra click to e.g. see the code examples). In the REPL it's a problem if the important part of the docstring gets hidden because your terminal is not tall enough and you have to scroll every time. But in the HTML you don't really have that problem.

As for doing it for your own docs: the only way to do it is to run a modified Documenter, since this would require changing the generated HTML based on the docstring contents (and might also require CSS and JS changes).

**Comment by halleysfifthinc** [comment]
Obviously I would need to modify Documenter. I was asking which part of Documenter I would need to modify to achieve this, but I think I've figured it out.
