### ISSUE TITLE
Markdown.Image does not render properly

### ISSUE THREAD

**Issue by Hydrotoast** [JuliaDocs/Documenter.jl#191]
Hi all,

I want to use `Markdown.Image` to render the results of `@eval` onto the page. I used [the example on the documentation](https://juliadocs.github.io/Documenter.jl/stable/lib/internals/expanders/#Documenter.Expanders.EvalBlocks). Unfortunately, the plots do not render properly.

My example project structure is as follows:

```
$ tree .
.
├── build
│   ├── assets
│   │   ├── Documenter.css
│   │   └── mathjaxhelper.js
│   ├── index.md
│   └── plot.svg
├── make.jl
├── mkdocs.yml
└── src
    └── index.md
```

The source for the example in `index.md`:

    ```@eval
    using PyPlot
    x = linspace(-π, π)
    y = sin(x)
    plot(x, y, color = "red")
    savefig("plot.svg")
    Markdown.Image("Plot", "plot.svg")
    ```

I compiled the document with `julia make.jl` and then built/served the documentation using

```
mkdocs build
mkdocs serve
```

Here is the rendering:

![documenter_markdown_image](https://cloud.githubusercontent.com/assets/246905/17653251/3314473a-6247-11e6-928e-7f45d32abf59.png)

**Comment by MichaelHatherly** [comment]
Looks like `Markdown.Image` is an inline element rather than a block element to you'll need to wrap it in a `Markdown.Paragraph` to make it render correctly:

```@eval
using PyPlot
x = linspace(-π, π)
y = sin(x)
plot(x, y, color = "red")
savefig("plot.svg")
Markdown.Paragraph(Markdown.Image("Plot", "plot.svg"))
```

The docs should be updated, not sure why it didn't include `Paragraph`. Might actually be best to use `Markdown.parse("![Plot](plot.svg)")` since `Paragraph` and `Image` aren't actually exported from `Base`.

As the note in the [Syntax](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@eval-block-1) suggests it's usually best to try to use `@repl` and `@example`. Do they not fit with what you're trying to do?

The issue with `nothing` showing up when `@eval` block return `nothing` will be fixed shortly on `master` and I'll tag a new point release.

**Comment by Hydrotoast** [comment]
Thanks @MichaelHatherly 

Within `@eval`, `Markdown.parse("![Plot](plot.svg)")` and `Markdown.Paragraph(Markdown.Image("plot.svg", "Plot")` renders the plots just fine. Note that this also fixes `nothing` being returned from `@eval` blocks in the issue linked.

Within `@example`, neither approach renders the plot. This may be considered a separate issue from the one I have reported. I have attached a screenshot of the behavior below.

![documenter_markdown_image2](https://cloud.githubusercontent.com/assets/246905/17672182/ebcb5358-62cf-11e6-8b95-848e38a53285.png)

**Comment by MichaelHatherly** [comment]
`@example` currently is just meant to return the text you'd see at the REPL/when displayed with `display`. There's not yet support for arbitrary MIMETypes. Best to use the approach found in https://juliadocs.github.io/Documenter.jl/latest/man/syntax/#@example-block-1 near the end of the section:

    ```@example
    using Gadfly # hide
    plot([sin, x -> 2sin(x) + x], -2π, 2π)
    draw(SVG("plot.svg", 6inch, 4inch), ans); nothing # hide
    ```

    ![](plot.svg)

if you want code plus the image it generates.

**Comment by Hydrotoast** [comment]
Okay, I would consider this bug closed then with a TODO item on updating the documentation.

**Comment by Hydrotoast** [comment]
Closing this issue now since the PR has been merged.
