### ISSUE TITLE
Can't view documentation in Safari

### ISSUE THREAD

**Issue by mkyl** [JuliaDocs/Documenter.jl#1985]
Hello `Documenter.jl` team,
Bit of a tricky issue, so please bear with me as I describe it. I'm happy to provide any additional details. A few days ago I stopped being able to view most hosted Julia documentation in my browser Safari Version 16.1 (18614.2.9.1.12). Whenever I try to open any documentation I get an empty viewport and the browser never finishes loading (see screenshot). Examples of documenter.jl sites that do *not* load:
- https://juliacollections.github.io/DataStructures.jl/stable
- https://juliafs.readthedocs.io/en/stable/stdlib/index.html
- https://jump.dev/JuMP.jl/stable/
- https://docs.julialang.org/en/v1/stdlib/Statistics/

Documenter.jl sites that do load:
- https://mkyl.github.io/QuasiStableColors.jl/stable/

At the 30 second mark the network pane of the browser inspector looks like this:
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/20482716/204933036-d9643331-9ccb-4f9a-8e29-4b2fe4c74d72.png">

The hanging occurs in private browsing mode too. I don't have an extensions installed.

**Comment by odow** [comment]
I can't reproduce this (with a slightly older version of Safari):

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/8177701/204934601-5c81bf2a-e943-4057-806b-0a16480bbdeb.png">

Are you behind any corporate firewall?

**Comment by mortenpi** [comment]
Your connections to [cdnjs](https://cdnjs.com/) are hanging for some reason. The fact that the docs do not load then is, while definitely not ideal, expected and known. It's just the way we organize the HTML here. _Technically_, not that it's helpful, if you wait for the 300s TCP timeout, the browser should eventually load the page.

It's hard to say why it's not loading for you though. A firewall is certainly a possibility. You should be able to try to debug it by going to one of the cdnjs URLs directly (they should normally initiate a file download), e.g.:

```
https://cdnjs.cloudflare.com/ajax/libs/juliamono/0.045/JuliaMono-Regular.woff2
```

I should note that this does make us quite vulnerable to CDN outages. It's just that it actually hasn't happened in practice for cdnjs (that I know of). But ideally we would probably want to see if we can load our assets asynchronously, so that you would fall back to at least a semi-functioning site if something does happen to the connection between your computer and cdnjs.

**Comment by mkyl** [comment]
Thanks for the quick reply! Had this issue occur behind a university firewall. Loading from home, I'm able to `curl` the URL @mortenpi provides and the page loads normally. I can retest this tomorrow behind that firewall. If that's the issue, I'll reach out to the university network admins. Closing this issue for now as it seems not related to `Documenter.jl` in particular.
