### ISSUE TITLE
Documenter ignores versions and keeps deploying 0.1 (0.1.4) instead of the new tags

### ISSUE THREAD

**Issue by tamasgal** [JuliaDocs/Documenter.jl#2036]
For some reason, Documenter got stuck on deploying v0.1.4 and linking it to v0.1 although we had tons of new version tags after that (currently we are at v0.9.0). This CI was triggered by the Julia Tag Bot when we released v0.9.0 but as you can see, Documenter is only caring abot v0.1 and v0.1.4:

https://github.com/JuliaHEP/UnROOT.jl/actions/runs/4124754507/jobs/7124401407#step:6:146

I tried the retagging trick by adding tags on old version tags with the `+docs` suffix (like suggested in https://github.com/JuliaDocs/Documenter.jl/issues/1786#issuecomment-1087573391) and it seemed to work (I repeated it for 0.8.14 and 0.9.0):

https://github.com/JuliaHEP/UnROOT.jl/actions/runs/4157789944/jobs/7192539887#step:6:133

Does anyone know what's going on? Is this a TagBot issue or some kind of a misconfiguration?

**Comment by mortenpi** [comment]
Yeah, I think you figured out the issue -- the TagBot-created tags don't trigger CI. And I think that is because you don't have `DOCUMENTER_KEY` set up correctly, since also the docs deployment is done with `GITHUB_TOKEN` as far as I can tell.

X-ref: https://github.com/JuliaRegistries/TagBot#ssh-deploy-keys

**Comment by tamasgal** [comment]
Ah alright. Could not see the forest for the trees... many thanks. The `DOCUMENTER_KEY` probably got lost during repo-transition ;)
