### ISSUE TITLE
Request for pointers on writing a plugin

### ISSUE THREAD

**Issue by tecosaur** [JuliaDocs/Documenter.jl#2095]
Hi,

I'm looking to make it easier to document instances of a special structure from a framework package of mine. I'm hoping that I can make a plugin to define a new documentation type, so similarly to

````
```@docs
thing
```
````

I can have

````
```@thingdoc
specialthing
```
````

The problem is, all I've been able to find on Documenter plugins in the documentation is the five sentences in https://documenter.juliadocs.org/stable/lib/internals/writers/#Documenter.Plugin 😬.

I'm hoping I could be given some pointers as to whether this is possible, and if so how I might go about it.

**Comment by mortenpi** [comment]
So, the short answer is that there isn't really any infrastructure for this in Documenter. It needs to be invented. But making Documenter more extensible is very much on my wishlist and roadmap. Some notes though:

* Passing `<: Plugin` objects to `makedocs` is the interface I think we want, for enabling plugins with some configuration. But we need ways for externally-defined `Plugin` objects to hook into to relevant parts.
* Documenter#master works by transforming a [MarkdownAST](https://github.com/JuliaDocs/MarkdownAST.jl) tree in steps. With that in mind, what I think we want for plugins is

  1. A way for plugin objects to hook into the Documenter pipeline between (some of) the standard build steps (see `Builder.jl`), and allow the plugin to do arbitrary transformations on the AST.

  3. Second thing we probably want to have is a way to register additional at-blocks that, when Documenter encounters them, it calls to a method defined on the plugin object that gets passed the at-block.

  Starting point could be just doing (1) or (2) -- (1) can be used to implement (2) for a given plugin. But (2) might be the slightly more constrained option, but one that is good enough for a majority of plugins.
* One additional question mark is hooking into rendering methods for custom AST objects. With the current code, it can be achieved by defining some methods (`HTMLWriter.domify` for HTML.. and there is a latex version of it as well). Might be good enough?
* This related PR has been stalling because I was a little unsure about the design (but it's about JS assets, rather than hooking into the pipeline): https://github.com/JuliaDocs/Documenter.jl/pull/1648
* I would also check what https://github.com/ali-ramadhan/DocumenterCitations.jl does (they hook into existing Documenter internals as far as I know).

Would be happy to hear your thoughts.

**Comment by tecosaur** [comment]
Thanks for the detailed response. 

One approach to renderer plugins that comes to mind is having a dict of block types and renderer functions, e.g. `Dict("docs" => (html=htmlfunc, latex=latexfunc), ...)` that can be extended. Perhaps the `makedocs` function could merge the default global dict with plugin-provided renderers. 

To make my initial request somewhat more concrete, I'm looking to make a `DataToolkitDocumenter` package which allows for a `dataset` docs type that generates a documentation box from the available information, something like this (quick mock-up):

![image](https://user-images.githubusercontent.com/20903656/229717061-b2ca34cb-a579-495d-8779-45aaeb3d2290.png)

**Comment by tecosaur** [comment]
Hmm, after having a look, it seems like the Documenter.jl system can already be extended in the way I was thinking without anything being done with Plugins, with only a little bit of boilerplate.

For reference, I've now got my documenter extension working: https://github.com/tecosaur/DataToolkitDocumenter.jl.

Some sort of guide might be nice for other people wondering what's required.

**Comment by mortenpi** [comment]
> Some sort of guide might be nice for other people wondering what's required.

Yeah, I believe the selectors approach was chosen back in the day precisely so that you could do this type of extending, and it's cool to see that it works for you. DataToolkitDocumenter is a great use case example we should keep in mind.

But the current approach has heaps of issues and limitations, in particular if you might have several plugins conflicting with each other, so I don't think we want to have that be the official way that gets locked down by semver. So this needs some proper design work to figure out a good API.
