### ISSUE TITLE
Increase relevance of (partial) exact matches

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/Documenter.jl#2203]
I played around a bit with the new search functionality and this is issue is essentially the same request as in https://github.com/JuliaDocs/Documenter.jl/issues/2141#issuecomment-1610927687

In 99% of cases I know the exact function I am looking for so it would be great to increase the importance of exact matches. As it is right now it is IMO a bit annoying since you essentially have to type out the whole name until you get a match.

**Comment by mortenpi** [comment]
Cc @Hetarth02

**Comment by mortenpi** [comment]
Then filtering in #2202 should also help with that a bit. It would actually be good to get a bit of feedback on that, whether that's good UX or not.

**Comment by Hetarth02** [comment]
I am confused about what the fuzzy search distance should be. If it is very much then one can get unwanted results and if its less(the case right now) we already know as mentioned above.

We should probably try out some distances with this, but I would suggest not going farther than 3.

**Comment by mortenpi** [comment]
I think the point here is that we want the matches that match exactly to be prioritized, and fuzzy matches shown a bit lower? The exact fuzzy distance in that sense is irrelevant here.

**Comment by Hetarth02** [comment]
Hmm, so basically a mix of exact and fuzzy searches could be a good thing...?

Like have top 10 or so searches which are exact matches and others with fuzzy, sound reasonable?

**Comment by Hetarth02** [comment]
Also, we might need to limit one or other search because either of them can have repetitive results which we don't want.

**Comment by mortenpi** [comment]
I feel that, ideally, repetitive results should be removed, rather than working around the problem by just throwing away (potentially) correct results because were hitting some arbitrary limit.

**Comment by fingolfin** [comment]
Just switched  <https://juliatesting.github.io/Aqua.jl/dev> to use Documenter 1.0, and tried the new search:
- `test_ambiguities`: unique hit found (yay)
- `test_ambiguitie`: unique hit found (yay)
- `test_ambiguit`: zero hits :-( -- old Documenter found this, down to `test_ambi`
- `test_amb`: one hit, but it is `test_all` (same as in old Documenter)

All in all I think that *perfect prefixes* need to be considered much more strongly...

(OK, old Documenter search also was weird; e.g. `test_ambiguit` gives a unique correct hit; `test_ambiguiti` (one letter more) suddenly things `test_all` also is a match; and `test_ambiguitie` (yet one letter more) suddenly has zero hits. WHAT?)
`

**Comment by digital-carver** [comment]
Minisearch has a separate [option](https://lucaong.github.io/minisearch/#md:search-options) for enabling prefix searches, so it looks like just adding `prefix: true` to [`searchOptions`](https://github.com/Hetarth02/Documenter.jl/blob/master/assets/html/js/search.js#L143) should be sufficient to solve this particular issue.

Instead of `true`, the option can also be passed a function, so that we search only when the user has entered [at least 3 letters](https://github.com/lucaong/minisearch/issues/203#issuecomment-1420358972).

They don't specify whether prefix-matched results are ranked lower than exact matches in their docs. It seems like that should be the case based on this [discussion](https://github.com/lucaong/minisearch/issues/129#issuecomment-1046908398), but that's worth verifying.

**Comment by Hetarth02** [comment]
Thanks for this, will probably look into it this weekend.

**Comment by mortenpi** [comment]
#2375
