### ISSUE TITLE
CI never seems to complete with Documenter 1.0

### ISSUE THREAD

**Issue by DanielVandH** [JuliaDocs/Documenter.jl#2264]
In https://github.com/DanielVandH/FiniteVolumeMethod.jl/pull/50, I'm testing the deployment with Documenter v1 vs. Documenter v0.27. In the v0.27 case [here](https://github.com/DanielVandH/FiniteVolumeMethod.jl/actions/runs/6207291546/job/16852393497), everything runs fine. In the v1 case [here](https://github.com/DanielVandH/FiniteVolumeMethod.jl/actions/runs/6207686086/job/16853117201?pr=50), it just never finishes. I don't think this is a fluke either, since I also noticed it a lot in a previous PR ([this one](https://github.com/DanielVandH/FiniteVolumeMethod.jl/pull/49), but I made pr50 to show this issue since there's too many commits in pr49).

Is there anything particular about the make.jl file that would be causing this in v1 versus v0.27? The make.jl is here https://github.com/DanielVandH/FiniteVolumeMethod.jl/blob/doc/docs/make.jl

**Comment by mortenpi** [comment]
I would guess that somehow the at-example blocks are getting stuck, which might be due to some IO blocking etc. I am not sure why 0.27 and 1.0 would be different here though -- I don't think we did much changes to the at-block evaluation.

What you could do is set `JULIA_DEBUG=Documenter` and re-run the CI. You should get more debug output, maybe pointing to where it's getting stuck.

**Comment by DanielVandH** [comment]
I turned on the debug, but nothing seems to happen:

https://github.com/DanielVandH/FiniteVolumeMethod.jl/actions/runs/6211290382/job/16860337346?pr=50

It's weird cause it works fine locally... Any other debugging ideas?

**Comment by mortenpi** [comment]
No good ideas. I would remove the `julia-actions/julia-docdeploy` action, since it does weird stuff, and see if anything changes. It might be eating up the debug output.

It does look like it gets stuck _somewhere_. So one option would be to try to make the process print a stack trace every now and then. This _might_ work for that:

```julia
Threads.@spawn begin
    @info "async sigkill loop started"
    while true
        sleep(10*60)
        run(`kill -SIGUSR1 $(getpid())`)
    end
    @info "async sigkill loop terminated"
end
```

**Comment by DanielVandH** [comment]
Thanks @mortenpi. I'll try it out and see.

**Comment by DanielVandH** [comment]
I tried removing docdeploy and the CI runs fine. Putting docdeploy back in and putting that thread you've given into make.jl, I get the output here:

https://github.com/DanielVandH/FiniteVolumeMethod.jl/actions/runs/6213368725/job/16864357366?pr=50

I don't really know what I'm reading from these logs. Does anything stand out to you?

**Comment by mortenpi** [comment]
> I tried removing docdeploy and the CI runs fine.

Then I would move the issue there and use the standard setup in the meanwhile. Nothing specifically stands out though. It looks like it's stuck in this functions somehow: https://github.com/JuliaDocs/Documenter.jl/blob/c3fc63b108feacf222e5ab98b1fb88231dc995a0/src/documents.jl#L905-L913

My best guess would be that it's the loading of GitHubActions.jl from a different environment brings in conflicting dependencies, and that just creates some weird behavior. But I am not entirely convinced of that either.

**Comment by DanielVandH** [comment]
I've posted it over on the docdeploy repo. Thanks for the help @mortenpi. I'll close this since it's not related to Documenter.
