### ISSUE TITLE
Build pages without adding them to sidebar?

### ISSUE THREAD

**Issue by tlnagy** [JuliaDocs/Documenter.jl#230]
When using the HTML output, is it possible to limit the depth of the content tree? Having a lot of pages makes the sidebar look ridiculous.

**Comment by MichaelHatherly** [comment]
Can you post an example if possible? Some idea of how big a "ridiculous" sidebar is would be useful to decide how to handle things here, thanks.

**Comment by tlnagy** [comment]
My word choice wasn't the best. What I meant was that the sidebar contained a large number of pages that aren't that important and end up cluttering the UI quite a bit. 
<img width="1472" alt="screen shot 2016-08-22 at 23 10 40" src="https://cloud.githubusercontent.com/assets/1661487/17882218/e9f3b9bc-68bf-11e6-8da9-49d29f207c5e.png">
<img width="1444" alt="screen shot 2016-08-22 at 23 26 13" src="https://cloud.githubusercontent.com/assets/1661487/17882221/edf3fe8c-68bf-11e6-9d42-e97eab748a1b.png">
<img width="1467" alt="screen shot 2016-08-22 at 23 26 23" src="https://cloud.githubusercontent.com/assets/1661487/17882228/f146df78-68bf-11e6-8a2a-f092591ca01f.png">

**Comment by MichaelHatherly** [comment]
> My word choice wasn't the best.

No, the word choice was good :) Perhaps we should have subsections in the navmenu "collapsed" by default.

**Comment by MichaelHatherly** [comment]
Another possibility: give the navmenu a separate frame so that it can be scrolled independently of the page body, similar to how GitBook does it. @mortenpi, how's that sound to you?

**Comment by mortenpi** [comment]
> Another possibility: give the navmenu a separate frame so that it can be scrolled independently of the page body

The navmenu would still have too much stuff though, so it might still be necessary to filter what gets into the navmenu in the first place.

However, making the navmenu scroll independent of the page is a good idea. Unfortunately the simple `display: fixed; overflow: auto` wasn't really working, since browsers (especially Safari) we're having some focusing issues. Having it scroll along like in [GitBook](https://www.gitbook.com/about) or the [Material MkDocs theme](https://squidfunk.github.io/mkdocs-material/) would definitely be an improvement though. I'll put it into #212.

On the initial issue, @tlnagy: would the third level pages (e.g. `Geom.bar`) be accessible via in-page links only then? We could introduce the system that all `.md` files get built, even if they're not in the navmenu, and you could then just drop the unnecessary pages from the navmenu. At some point we decided to be consistent with MkDocs and ignore pages that are not in `pages`, but I'd be open to changing that.

Having level three and deeper links in the navigation menu collapsed by default sounds like a good idea in any case though.

**Comment by MichaelHatherly** [comment]
> At some point we decided to be consistent with MkDocs and ignore pages that are not in `pages`, but I'd be open to changing that.

I'm fine with changing that as well.

**Comment by tlnagy** [comment]
> On the initial issue, @tlnagy: would the third level pages (e.g. Geom.bar) be accessible via in-page links only then? We could introduce the system that all .md files get built, even if they're not in the navmenu, and you could then just drop the unnecessary pages from the navmenu. At some point we decided to be consistent with MkDocs and ignore pages that are not in pages, but I'd be open to changing that.

I haven't had any feedback from other Gadfly contributors yet, but that's what I would like to do. I have pages like this:

<img width="1454" alt="screen shot 2016-08-23 at 11 47 50" src="https://cloud.githubusercontent.com/assets/1661487/17905344/84cbb25c-6927-11e6-873d-378e4bcbe3af.png">

that link to all the pages. I think most people wouldn't mind the extra click to switch between different Geometries if, in exchange, the navbar was much less cluttered. What do you think?

**Comment by MichaelHatherly** [comment]
Yes, that approach looks good &mdash; just keep the "main" topics easily reachable from the navmenu and have the others reachable through in-page contents seems like a good compromise to me.

**Comment by tlnagy** [comment]
Probably the best thing for Gadfly's Docs would be to have the ability to specify pages that should be built, but not added to the `sidebar`. I think that would work really well.

**Comment by tlnagy** [comment]
Here's a live version of the Gadfly docs I'm working on: http://tamasnagy.com/Gadfly.jl/.

@MichaelHatherly @mortenpi If you guys get a chance could you take a look and see what you all think? I think I'm not going to merge until I can reduce the amount of clutter in the sidebar.

**Comment by MichaelHatherly** [comment]
What would work fine for Gadfly's docs is perhaps to move the `man/guides.md` etc. files to `lib/guides.md` etc. and remove the `"guides" => load_dir("guides"),` lines from `make.jl` and just have the individual pages available through the in-page `@contents` block.

Currently that doesn't work of course, since only pages in `pages` get rendered, but that should probably be changed (as mentioned above): render all `.md` pages found in `src` regardless of whether they're in `pages`. @mortenpi will you have a chance to look into that?

**Comment by mortenpi** [comment]
Can do, some time today.

There's the matter of being consistent with MkDocs though, which ignores page not in the YAML file IIRC. Also, what about pages that are completely disconnected (i.e. no links to them) -- should we try to find them and warn the user?

One alternative would be a user-defined list of non-navbar pages, most likely as a separate variable (`hidden_pages`?).

**Comment by MichaelHatherly** [comment]
> should we try to find them and warn the user?

Would be good to do at some point, doesn't need to be implemented initially though.

> One alternative would be a user-defined list of non-navbar pages, most likely as a separate variable (`hidden_pages`?).

If we can avoid having to add another config setting that would probably be better. Shall we just see how things go with rendering non-nav pages and see whether we need something extra after that? It's probably not worth tying ourselves completely to how MkDocs does things I think.

**Comment by tlnagy** [comment]
> Also, what about pages that are completely disconnected (i.e. no links to them) -- should we try to find them and warn the user?

I think this would be a nice feature to have. Because there is bound to be accidentally orphaned pages.

> There's the matter of being consistent with MkDocs though, which ignores page not in the YAML file IIRC.

IMO, this isn't the best behavior. Depends on the organization of the docs.

**Comment by mortenpi** [comment]
Hmm, actually just building these missing pages might not be the wisest idea. They would be completely disconnected from the navigation tree, which is the basis for the top and bottom links and our ability to style the current page in the navigation menu differently.

While such completely disconnected pages might have some use to someone, I don't think that's the use case here -- they still belong under something (e.g. the "Geometries" page).

Instead I would propose we still keep them in the navigation tree, but hide them when rendering the sidebar. But it would probably be nice to have it more fine-grained that just limiting the tree depth. I have the following in mind:

Say the nav. structure should be
```
- A
- B
  - x
  - y
  - z
- C
```
and `x`/`y`/`z` should be hidden. One option would be to specify this in `pages`:

```
pages = [
  "A",
  "B" => Hidden(["x", "y", "z"]),
  "C"
]
```
B would be a clickable link in the sidebar then (not sure what the URL/filename should be though). We could even have two `Hidden`s:

1. `Hidden(page, subpages)` -- builds `page` for B
2. `Hidden(subpages)` -- creates a placeholder page automatically, probably a simple `@contents` block.

Or perhaps, just `Hidden(page, subpages)` and do `isfile(page) ? use(page) : generate(page)`. Would solve the URL/filename issue.

An alternative would be to introduce a new `@meta` block entry `SubPages`, where you could specify a list of these hidden subpages. These `@meta` blocks should then be parsed right after loading the pages in `pages` and these additional pages loaded and the navigation tree updated. `SubPages` in a hidden sub-page could be an error.

In both cases there would be the question of how the top/bottom links nad sidebar styling should be handled. I would propose:

- If you're on `x`/`y`/`z`, make `B` the current page in the sidebar. (I am not sure about how to handle the in-page headings though.)
- If on `x`/`y`/`z`, the next/prev should point to other hidden pages (e.g. `x`/`z` if on `y`; and `prev=B` if on `x`, `next=C` if on `z`). Next from B should be `x`. However, prev from C could be B to be consistent with the sidebar.
- On `x`/`y`/`z` the top links should go e.g. `B >> x` (the pages now clearly belong under B).

In both cases the orphaned pages issue would be solved as well, since the pages would have to be specified in `pages`.

**Comment by MichaelHatherly** [comment]
Or perhaps just a naming scheme for markdown files that should be "hidden". Maybe a `_` prefix, i.e. `_hidden_file.md`.

**Comment by tlnagy** [comment]
Thanks @mortenpi for thinking about this

> `Hidden(page, subpages)` -- builds `page` for B

This sounds like the best idea.

> I would propose

Those sound good, except I would not overcomplicate next/prev. I would probably just next/prev ignore hidden pages and have next/prev on `x` show `A` and `C` since it is part of `B`
