### ISSUE TITLE
GitHub Actions workflows for downstream testing

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#2314]
The goal would be to set up standard CI workflow that we could use to downstream-test some packages and documentation builds. These would act as canaries for any breaking changes to internal we might be doing:

- [ ] A couple of candidates for packages: DocumenterCitations, DocumenterMermaid (pick a commit, run the package's test suite, but with Documenter#master as dependency)
- [ ] We could also try to build some documentations, but not sure who are good candidates. The ones that would be good canaries (like JuMP) are very expensive to build.
- [ ] If we can, we could also try to build the Julia manual. Maybe we can just pull the tarball of the latest release? This is also a bit expensive, but possibly worth it.

For the more expensive downstream tests, we could add some [concurrency options](https://docs.github.com/en/actions/using-jobs/using-concurrency) to avoid too many unnecessary builds.

It's a nice self-contained issue for anyone who wants to dabble with GitHub Actions.

**Comment by odow** [comment]
JuMP (and MathOptInterface) have a set of `workflow-dispatch` tests that can be run on-demand:
 * https://github.com/jump-dev/JuMP.jl/blob/master/.github/workflows/extension-tests.yml
 * https://github.com/jump-dev/MathOptInterface.jl/blob/master/.github/workflows/solver-tests.yml

We always run these before tagging each release, and we optionally run them on PRs of concern that may have downstream effects.

Here's a recent example where it was useful: https://github.com/jump-dev/MathOptInterface.jl/pull/2318. The changes in that PR are not publicly breaking, but they add new features, and because of the opt-out nature of JuMP's testing system, it initially caused downstream solvers to start running (and failing) a new set of tests.

**Comment by mortenpi** [comment]
`workflow-dispatch` is a great idea for the expensive builds!
