### ISSUE TITLE
Remove CI-dependent `prettyurls` and recommend LiveServer.jl? 

### ISSUE THREAD

**Issue by gdalle** [JuliaDocs/Documenter.jl#2395]
See the discussion in https://github.com/JuliaCI/PkgTemplates.jl/pull/450#discussion_r1446173607

**Comment by mortenpi** [comment]
Is there anything more actionable here? PkgTemplates change has been made, and we do suggestion using LiveServer (although maybe it could be more prominent):

https://github.com/JuliaDocs/Documenter.jl/blob/223102fa86558652d2819f13687c7839614c2546/docs/src/man/guide.md?plain=1#L146-L151

**Comment by goerz** [comment]
There are a couple of places where the documentation should be revised:

* The Note at the end of the section [Building an Empty Document](https://documenter.juliadocs.org/stable/man/guide/#Building-an-Empty-Document): Either remove the "Alternatively..." paragraph altogether or at least rephrase it with a warning: "For simple projects, it may be suitable to set `prettyurls` on the fly depending on whether the documentation is being built locally or, e.g., in a Github Action (see Hosting Documentation): [code]. This offers the benefit of making the documentation easy to view locally while still deploying with the recommended URL scheme. However, be aware there can be subtle differences between `prettyurls=true` and `prettyurls=false` when advanced features like `@raw` blocks are being used. In such cases, it is best to maintain a consistent setting."
* In the docstring of [`Documenter.HTMLWriter.HTML`](https://documenter.juliadocs.org/stable/lib/internals/writers/#Documenter.HTMLWriter.HTML), remove the last paragraph "To have pretty URLs disabled in local builds..."

I can probably open a PR for these.

To be fair, the change in `PkgTemplates` was the more critical one, though, since that's where people got the setting without understanding the consequences. If someone wants to *deliberately* set `prettyurls` depending on the CI variable, that's fine.

**Comment by gdalle** [comment]
I think this advice deserves to be highlighted in several places, cause the PkgTemplates change broke links for everyone who, like me, used to build docs with include. Plus LiveServer doesn't always work, and when it doesn't it's unclear what people should do to get correct links in this brave new world

**Comment by goerz** [comment]
> I think this advice deserves to be highlighted in several places

The advice to use `get(ENV, "CI", nothing)`, or the advice to avoid it?

> the PkgTemplates change broke links for everyone who, like me, used to build docs with include.

Can you elaborate on that? What broke?

> it's unclear what people should do to get correct links in this brave new world

Probably too sacrilegious to put in any official Julia documentation, but personally, I still use the `alias serve='python -m http.server'` in my `.bashrc` more often than `LiveServer`.

**Comment by gdalle** [comment]
> The advice to use get(ENV, "CI", nothing), or the advice to avoid it?

The advice to use LiveServer for people who build docs locally and were accustomed to `include("docs/make.jl")`

> Can you elaborate on that? What broke?

I think the links in the sidebar pointed to nonexistent pages with `prettyurls=true` when I built locally.

**Comment by goerz** [comment]
> The advice to use LiveServer for people who build docs locally and were accustomed to `include("docs/make.jl")`

I agree. That should be mentioned in both places.

> I think the links in the sidebar pointed to nonexistent pages with `prettyurls=true` when I built locally.

That should never happen. Did you clear the browser cache and remove the `docs/build` folder? No matter whether `prettyurls` is `true` or `false`, if you `include("docs/make.jl")`, the result should work perfectly if viewed locally with `LiveServer` or `python -m http.server`. Anything else would be a pretty serious bug. The only problem with setting `prettyurls` dynamically depending on the `CI` variable is that the documentation might be correct locally but be subtly broken when deploying from CI, or vice versa. Like, if you refer to assets from `@raw` blocks, the correct relative path for these assets might be different depending on `prettyurls`.

**Comment by gdalle** [comment]
Oh right, the thing is I try to view locally by double-clicking `docs/build/index.html`

**Comment by goerz** [comment]
Yes, that will indeed not work. It's good enough to check a particular page, but as soon as you want to navigate between pages, it's best to get in the habit of running a local web server, no matter what the `prettyurls` setting is.

I just opened #2402. Feel free to change any of the text.

I kept the mention of `prettyurls = get(ENV, "CI", nothing) == "true"` but added a discussion of the caveats. It makes the Note-block in the Package Guide a bit long, maybe, but it's probably not a bad idea to explicitly discuss that code snippet, given how widespread it is due to having been the default in `PkgTemplates`.

I guess we'll see how many "complaints" we from people who start new packages, try to preview the documentation by double-clicking an `.html` file, and then find the links not working. We might have to figure out a way to place the recommendation for `LiveServer` more prominently. But let's see.
