### ISSUE TITLE
HTML rendering issues with Julia 0.4

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaDocs/Documenter.jl#246]
I found some issues when using Julia 0.4 with the HTML engine, which do not show up with Julia 0.5. I'm using version 0.3.1.

Up to now, I found 2 issues:

* admonitions (`!!! note` ) are not rendered. Example:

----------------------------
![note_0 4_vs_0 5](https://cloud.githubusercontent.com/assets/223753/18115607/f9ef2bf8-6f40-11e6-81e8-ce051d3b336c.png)
---------------------------

* inline quoted text ends up taking the whole line when used inside lists, which screws up the formatting of course. Example:

--------------------------------
![list_0 4_vs_0 5](https://cloud.githubusercontent.com/assets/223753/18115630/2804f3ce-6f41-11e6-8962-b52d3bbcc5bd.png)
-------------------------------

**Comment by MichaelHatherly** [comment]
Both are just differences with `Base.Markdown.parse` since I only added Admonitions and proper nested lists quite recently (https://github.com/JuliaLang/julia/pull/17272 and https://github.com/JuliaLang/julia/pull/17359). Not much can be done about backporting the changes since they're new features rather than bugfixes.

**Comment by carlobaldassi** [comment]
I see, thanks.
