### ISSUE TITLE
Documenter might not be expanding the example blocks in docstrings

### ISSUE THREAD

**Issue by Azzaare** [JuliaDocs/Documenter.jl#2486]
Hi there,

I have stumbled upon an issue while using DocumenterVitepress.jl, and based on https://github.com/LuxDL/DocumenterVitepress.jl/issues/79#issuecomment-2017137547 , it might be something fixable only in Documenter.jl.

To be fair, my knowledge of Documenter internal is quite low, so I am not sure if this is a bug or something akin to a feature request. Any assistance would be appreciated anyway.

**Comment by mortenpi** [comment]
This is intended behavior -- most of the at-blocks don't make sense within docstrings since they're dynamic, and there's no (easy) way to render them correctly in the REPL. Getting evaluated code snippets into docstrings should be done either with doctests, or in DocStringExtensions style. Otherwise, I would just suggest linking from the docstrings to the manual, for more fancy examples.

X-ref: #1859

**Comment by Azzaare** [comment]
Thank you for the prompt answer.
