### ISSUE TITLE
Make rendering of doctest output optional

### ISSUE THREAD

**Issue by tlycken** [JuliaDocs/Documenter.jl#252]
I guess it's a matter of style, but the output section in most of my documentation snippets is very uninteresting, and mostly clutters the reading experience. It would be nice to be able to suppress the output of `# output` and anything following :)

**Comment by MichaelHatherly** [comment]
Is this for docstrings within Julia source files or in the external markdown files?

We can't do any suppression within docstrings since that content should always be able to be viewed correctly independent of `Documenter`.

For doctests in the external markdown files perhaps see if the `@example` and `@repl` blocks are of any use for you needs, since you don't have to worry then about manually writing out the expected output for each block. These blocks allow for the output of individual lines to be hidden using `# hide` comments. (There's some examples of there use in the [Syntax](https://juliadocs.github.io/Documenter.jl/latest/man/syntax.html) section of the manual.)

**Comment by tlycken** [comment]
I'm using it only in markdown files for now, so even if suppression within docstrings is off the table there is some value for me in it :)

`@example` blocks might very well be good enough, though, but I really liked how the doctests share no context at all - if I understand the documentation correctly, all `@example` blocks essentially build up a single, continuous Julia session?

**Comment by MichaelHatherly** [comment]
> blocks essentially build up a single, continuous Julia session?

No, they are also sandboxed in anonymous modules, though you can share state by "naming" the `@example` or `@repl` with `@example name` and `@repl name`.

**Comment by fredrikekre** [comment]
Perhaps
````
```jldoctest; output=(true|false)
foo(a, b) = a + b
foo(2, 3)

# output

5
```
````
which would still test the result, but hide the output in the rendered docs? I think `julia>` style doctests should be unaffected by `output` since you can just append a semicolon instead.

**Comment by fredrikekre** [comment]
Note that this suggestion would still render "correctly" even if used in docstrings, but of course the output would still be there (which is fine).
