### ISSUE TITLE
Option to Disable collapse/expand

### ISSUE THREAD

**Issue by AnzhiZhang** [JuliaDocs/Documenter.jl#2550]
#1393 and #2078 added functionality to collapse/expand docstring blocks. However, I and some potional users may perfer to disable this feature, especilly it is so easy to collapse accidentally (#2204). For another example, I would also like to disable collapse in code reference pages (see also #2133).

_Originally posted by @AnzhiZhang in https://github.com/JuliaDocs/Documenter.jl/issues/2204#issuecomment-2266301009_

**Comment by fredrikekre** [comment]
I agree it is a bit annoying when you do collapse by accident, but after https://github.com/JuliaDocs/Documenter.jl/pull/2551 this should be pretty rare.

I personally don't think there has to be an option to disable this. Seems a bit "reader hostile" to deny readers the possibility just because the author don't like it?

**Comment by AnzhiZhang** [comment]
> after #2551 this should be pretty rare.

Agreed, I will close this issue. After that, only the arrow icon is related to this feature - which means it is disabling the icon and there is no reason to do so.
