### ISSUE TITLE
Format.HTML locally, mkdocs when hosted

### ISSUE THREAD

**Issue by timholy** [JuliaDocs/Documenter.jl#265]
In [ImageCore](https://github.com/JuliaImages/ImageCore.jl), when I build the docs locally I'm getting the Documenter HTML format because [I've configured it that way](https://github.com/JuliaImages/ImageCore.jl/blob/master/docs/make.jl). However, the hosted docs are still in the blue "mkdocs" format: https://juliaimages.github.io/ImageCore.jl/latest/.

Secondarily, do I still need a `mkdocs.yml` file if I am using Documenter's own HTML? In another similarly-configured repo, [ImageFiltering](https://github.com/JuliaImages/ImageFiltering.jl), I omitted that file and did a build (with Documenter debugging on), but it complained: https://travis-ci.org/JuliaImages/ImageFiltering.jl/jobs/159683982 (scroll down to the bottom and expand the triangle).

Any ideas? I skimmed Documenter's docs again but did not see answers to those questions.

**Comment by MichaelHatherly** [comment]
For HTML deployment you'll need to follow the same approach used in Documenter's own `deploydocs` (https://github.com/JuliaDocs/Documenter.jl/blob/4dcfa29bf730306ba6b89b849aa96d2448df2298/docs/make.jl#L44-L49). Eventually HTML deployment will be the default configuration for `deploydocs`, but that'll need a deprecation over several releases probably.

`mkdocs.yml` can be removed if you're building our native HTML output. All configuration is just done in the `make.jl` file.

`ImageCore`'s docs aren't building since by default `deploydocs` deploys from `nightly`, which appears to be failing in tests. Probably best to deploy from `0.5` with

```julia
deploydocs(
    # ...    
    julia = "0.5",
    # ...
)
```

**Comment by timholy** [comment]
Thanks! Would you like me to add it to the "Guide"? Or do you folks have other plans for where to put that information?

**Comment by MichaelHatherly** [comment]
No plans just yet, once HTML is the default then the guide and hosting pages will need some reworking. For the moment though probably just a short note in the "Native HTML output" block in the https://juliadocs.github.io/Documenter.jl/latest/man/guide.html#Output-formats-1 section about what's needed in the `deploydocs` call to make HTML work properly.

**Comment by tlnagy** [comment]
I also ran into this problem, glad the docs have been updated.
