### ISSUE TITLE
No docs generated for `DSGE`

### ISSUE THREAD

**Issue by emoszkowski** [JuliaDocs/Documenter.jl#329]
I'm trying to make docs for DSGE.jl, but makedocs isn't able to generate the proper documentation. Everything works fine locally, but I'm encountering an issue with the travis build.  Is there something that I'm overlooking here?

Here's the build link: https://travis-ci.org/FRBNY-DSGE/DSGE.jl/builds/168400136

**Comment by MichaelHatherly** [comment]
The [`strict` keyword](https://github.com/FRBNY-DSGE/DSGE.jl/blob/9cb2e6a9fc04a739bd223bdb4bc1e25f1b55c0ee/docs/make.jl#L9) is the problem. Building docs in `strict` mode will fail whenever there are any warnings during the build, namely missing docs and invalid `@ref` links. You'll need to resolve those warnings before the build will complete, or just remove the `strict = true` since it is currently undocumented and still considered experimental (same goes for `linkcheck` as well).

**Comment by emoszkowski** [comment]
Great, thanks. I tried switching those, and the docs still aren't deploying. There are no errors that I can discern. Here's the most recent build: https://travis-ci.org/FRBNY-DSGE/DSGE.jl/builds/168452564

**Comment by MichaelHatherly** [comment]
Are these not them: https://github.com/FRBNY-DSGE/DSGE.jl/tree/gh-pages/latest?

The message at the end of the `deploydocs` stage:

```

**Comment by emoszkowski** [comment]
So it looks like the HTML files get generated, but I'm unclear on what to do to actually see the website. I followed the instructions for adding the shields to the README, but they don't seem to go anywhere.

**Comment by emoszkowski** [comment]
I notice that in Documenter.jl's repo, there's an index.html file containing the url for the github.io site. Do I need to provide one of those? Also, it seems like the gh-pages branch in the Documenter.jl repo only has the documentation and none of the source code. Could that be causing problems?

**Comment by MichaelHatherly** [comment]
The main page should always be named `index.md` so that when a user goes to `https://frbny-dsge.github.io/DSGE.jl/latest/` they get redirected to `https://frbny-dsge.github.io/DSGE.jl/latest/index.html`. If you use a different name such as https://frbny-dsge.github.io/DSGE.jl/latest/intro.html then you'll just need to adjust your links in the README and anywhere else that you've left off the `intro.html` part. I'd strongly recommend using the standard `index` naming convention though to make it easier for new users to navigate the docs.

> I notice that in Documenter.jl's repo, there's an index.html file containing the url for the github.io site. Do I need to provide one of those?

Do you mean: https://github.com/JuliaDocs/Documenter.jl/blob/gh-pages/index.html? That one isn't needed really, but it allows http://juliadocs.github.io/Documenter.jl to redirect to the stable docs at http://juliadocs.github.io/Documenter.jl/stable which is a little nicer for navigation purposes. Not strictly necessary though.

> Also, it seems like the gh-pages branch in the Documenter.jl repo only has the documentation and none of the source code. Could that be causing problems?

Won't cause problems, but none of that content apart from the `latest` directory (and `stable`, or the other versioned directories once you have them) need to be on the `gh-pages` branch. Best to just remove the other content to keep things tidy.

**Comment by emoszkowski** [comment]
Got it, thanks so much!

**Comment by MichaelHatherly** [comment]
Great, glad it's working now. Would be good to have the DSGE.jl docs listed in https://juliadocs.github.io/Documenter.jl/latest/man/examples.html.
