### ISSUE TITLE
Documentation not generated for a tagged version

### ISSUE THREAD

**Issue by juliohm** [JuliaDocs/Documenter.jl#345]
I recently updated my package to v0.4.0 but the documentation was not built for it: https://github.com/juliohm/ImageQuilting.jl/tree/gh-pages

Could you please explain what is the cause of the issue?

**Comment by MichaelHatherly** [comment]
Looks like the `0.5` Linux build failed before it could start building the docs for `0.4.0`: https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/167815408. Since Documenter is generally the last thing to be run on Travis any build failure is going to skip the docs deployment phase.

Since that tag is already public and in `METADATA.jl` I think the best approach to getting the docs for `0.4.0` onto your `gh-pages` branch would be to do it manually as follows:

- checkout the commit a05e22acd7058bec5962cacf3ffe2820a6472491 locally;
- run `julia docs/make.jl` and `mkdocs build`;
- clone the `gh-pages` branch to somewhere;
- copy the contents of `docs/build` to the `stable` folder in the new clone;
- also copy `docs/build` to a new `v0.4.0` folder;
- commit and push those changes back to GithHub.

I think that should be all that's needed to get things sorted.

**Comment by juliohm** [comment]
Interesting, thank you for the detailed instructions. I thought Documenter.jl was somehow checking all the tags in GitHub even if the build has failed at some point. I will decide if I add the docs manually or just tag a new patch version. I am inclined to the latter option.

**Comment by juliohm** [comment]
The documentation of my package is not been built anymore even for latest (master branch). I don't know what is wrong with the setup, Travis tests show success in every command.

Can you please help me debug this issue?

**Comment by MichaelHatherly** [comment]
Failing due to the removal of the `journal` theme from the default MkDocs installation most likely:

- https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/172840519#L785 (deprecation warning)
- https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/174970957#L777 (missing theme error)

**Comment by juliohm** [comment]
On the spot @MichaelHatherly, thank you.
