### ISSUE TITLE
Travis build stalls on 0.5 when make.jl is run

### ISSUE THREAD

**Issue by KristofferC** [JuliaDocs/Documenter.jl#375]
Due to my package suddenly started failing on nightly I swapped to using 0.5 for the build (https://github.com/KristofferC/ContMechTensors.jl/commit/593ce54b36cf25e83ee8b32459b4dccb1d643797).

However, the build now seems to stall https://travis-ci.org/KristofferC/ContMechTensors.jl/jobs/184179783#L200.

Any help debugging this is appreciated.

**Comment by MichaelHatherly** [comment]
Can you add an environment variable `DOCUMENTER_DEBUG` with value `true` to the travis settings for that page.

The stalling has happened before, though not sure whether it's the same cause since I don't think anything relevant has been changed.

Could possibly just be an intermittent problem perhaps, hopefully. Maybe rebuild the commit a couple of times to see if it happens every time.

**Comment by KristofferC** [comment]
Looks like it was just intermittent. Sorry I should have rebuilt a couple of times first before reporting. https://travis-ci.org/KristofferC/ContMechTensors.jl/jobs/184179783
