### ISSUE TITLE
LaTeX/equation issue

### ISSUE THREAD

**Issue by cormullion** [JuliaDocs/Documenter.jl#428]
If I'm reading the documentation correctly, I think this should be valid LaTex:

```
    ```math
    \frac{\sqrt{(3)} radius}{2}
    ```
```

But in the finished output, I'm seeing:

![screen shot 2017-02-15 at 15 36 31](https://cloud.githubusercontent.com/assets/52289/23013006/b819abf8-f420-11e6-9dff-933e4c6708e0.png)

**Comment by tkoolen** [comment]
I'm not a contributor to this package, but I believe you need to escape special characters (`\\` instead of `\`, `\$` instead of `$`), *unless* you use the
```
doc"""
math block here
"""
```
syntax (`@doc_str` string macro). See http://docs.julialang.org/en/stable/manual/documentation/?highlight=doc_str#syntax-guide. But then you can't use normal string interpolation.

**Comment by cormullion** [comment]
Thanks, that's interesting. I copied that syntax from the [Documenter manual](https://juliadocs.github.io/Documenter.jl/latest/man/latex.html#Julia-0.5-1), so I wasn't sure whether it was a syntax issue or something else.

**Comment by tkoolen** [comment]
They do mention the escaping thing here: https://juliadocs.github.io/Documenter.jl/latest/man/latex.html#Escaping-characters-in-docstrings-2.

**Comment by mortenpi** [comment]
I didn't notice that it was documented in the base docs. I this case I wouldn't consider it a bug, since it seems that a decision has been made that we should support special characters in normal docstrings (and you can work around it using `@doc_str`).

Probably wouldn't hurt to mention it in the [LaTeX section](http://docs.julialang.org/en/stable/manual/documentation/?highlight=doc_str#id1) of the main manual, and also perhaps mention in Documenter's manual that some care should be taken when copying stuff between Documenter's `.md` files and docstrings.

**Comment by cormullion** [comment]
Yes the differences between the Markdown and source syntaxes had escaped me, so perhaps a note would help others too.
