### ISSUE TITLE
How to get docstrings from functions in Main

### ISSUE THREAD

**Issue by denizyuret** [JuliaDocs/Documenter.jl#432]
I have a bunch of functions in MyModule, another bunch in Main that I would like to use @docs with.
* If I don't specify modules in makedocs things work fine but I don't get warnings for MyModule.
* If I set modules=[MyModule, Main] I get a ton of warnings because of Main.
* If I set modules=[MyModule], makedocs cannot find the docstrings in Main functions.

The last one surprised me, I thought modules=[...] was only for generating warnings, why does it effect whether docstrings are found?

**Comment by mortenpi** [comment]
Sorry for a late reply, I didn't have an answer right away so it ended up on a back burner.

What do you mean by having functions in `Main`? Do you mean extending functions in e.g. `Base` or other packages? When building package docs the `Main` should basically be the `make.jl` file, and if you're documenting a package then you shouldn't have any functions there.

To get your docstrings for functions extending functions from e.g. `Base`, you should be able to do `Base.foo`. And this should exclude the docstrings from `Base` and only take docstrings from `MyModule`.

In any case, an example where the issue comes up might be best.
