### ISSUE TITLE
Fix discrepancies in Windows build

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#444]
Following up on #434:

- [x] Remove backslashes from links in Windows build (#434).
- [ ] Add tests for backslash handling.
- [ ] Method ordering differs.

@tkelman: do you have an example of a page where the method ordering thing happens?

**Comment by tkelman** [comment]
Between successive builds even on linux 64, the search index `doc/_build/html/en/search_index.js` seems to change a bit in method ordering: https://github.com/tkelman/julia/commit/e85340d8f3a051e4770db856ae25e91b58b1b168#diff-c70072a0ebb124fa8d24e0a1dcf6a9f2

Here's the diff between the docs built on windows 64 vs linux 64: https://github.com/tkelman/julia/commit/da5bf475f435c2fceb105b31719f371175f154bd
(or https://gist.github.com/a1d00abf8cc9b2d6d0b552e6215cc266 as a messy rebase with a bunch of conflicts)

Many of these differences are commit sha's in links, but not all - some are different method signatures. Let me rearrange the way I do these to try to make it a cleaner diff.

**Comment by tkelman** [comment]
Here's a much better version where I managed to get rid of the sha change parts of the diff: https://github.com/tkelman/julia/commit/bd5f4ae0fb675275b8fbab09cb4ba883f77bded4

**Comment by mortenpi** [comment]
Is the method ordering in Julia's docsystem consistent between builds? I easily could have missed something, but as far as I can tell Documenter uses the ordering Julia provides. The fetching of docstrings from Julia happens [here](https://github.com/JuliaDocs/Documenter.jl/blob/master/src/DocSystem.jl#L299-L307) I believe.

**Comment by tkelman** [comment]
Is a slightly different method used for the search_index? What we might want to try is running from the same commit, same platform, re-bootstrap and regenerate docs multiple times and compare. I'm not sure whether it's supposed to be deterministic in terms of the way the system image and method tables are stored internally, or if there are things that depend on memory address etc. I haven't run through this process all that many times, but anecdotally from the builds I've looked at I think most of the linux builds have been showing a certain signature for links that the windows build usually picks differently. So there's probably some platform-specific bias? Or just differing methods elsewhere due to `is_windows` etc blocks and otherwise OS-dependent API's in Base might make change the whole method table ordering, but consistently.

**Comment by odow** [comment]
This issue is old and stale, and I think it could be closed. Does it matter if there is a difference between windows and linux builds?

**Comment by mortenpi** [comment]
> Does it matter if there is a difference between windows and linux builds?

I think the generated HTML should generally be identical. If there are difference, then the Windows build is likely broken in some way (e.g. invalid path separators). But I don't think this specific issue is actionable, so let's clone.
