### ISSUE TITLE
Documenter.css case is wrong

### ISSUE THREAD

**Issue by haberdashPI** [JuliaDocs/Documenter.jl#507]
My HTML generated documentation is [missing the css file](https://haberdashpi.github.io/Weber.jl/latest/). The file is referencing "documenter.css" but the generated file is "Documenter.css".

I've looked through the source and see that these cases are indeed different during generation and when sources are copied, so it looks pretty easy to fix, but I don't have the time at the moment to actually create a decent pull request. It's also not clear why it doesn't work for me but works fine for other projects... so maybe something else is wrong???

**Comment by mortenpi** [comment]
This is quite bizarre. You're deploying from OS X I see, so that is different from most other setups, although I don't see why OS X should randomly capitalize filenames. I don't have access to a mac.. could try and see if you can reproduce it locally?

The copy happens [here](https://github.com/JuliaDocs/Documenter.jl/blob/v0.11.1/src/Writers/HTMLWriter.jl#L114), and the file has an all lowercase name in the repo.

**Comment by haberdashPI** [comment]
Aye, it is, bizarre. I haven't had a linux machine to troubleshoot my package installation and there are some somewhat tricky binary dependencies so I've stuck with OS X. 

When I run `julia make.jl` on my local machine I don't see this problem, the generated file is "documenter.css". I will try and dig into this a little more when I have some time tomorrow and see what I can find.

**Comment by haberdashPI** [comment]
Okay, I think I understand more about what is happening, but I still don't see how to fix it.

If you go to the [github page](https://github.com/haberdashPI/Weber.jl/tree/gh-pages/latest) for the `latest` documentation folder, it appears that mkdocs is still being used to deploy my documentation on travis. Or at least, the directory layout looks the same as when mkdocs is used, and on my local machine the layout when using HTML output looks quite different. (FYI: I just changed from using mkdocs to trying out the new HTML output).

I suspect there is something wrong with my call to `deploydocs`?? But I don't see what. The only thing I've changed from Gadfly (the project I used as an example to setup HTML output) is the version for Julia from 0.5 to 0.6 and "linux" to "osx", and those docs deploy just fine to HTML. My understanding is that `makedocs` should clean out the build directory by default, so I don't understand why there should be anything left from prior builds using mkdocs.

**Comment by mortenpi** [comment]
OS X filesystem is case *in*sensitive, right? My guess right now is that since you have the capitalized `Documenter.css` from the old builds, then when Documenter `git add`s the new files, it doesn't recognize `documenter.css` as a new file and keeps that capitalization for it.

If would be great if you could verify this theory. On Ubuntu for

```sh
git init
touch File && git add File
git commit -m"C 1"
git rm File
echo "asdf" > file
git add file
git status
```

I get 

```
	deleted:    File
	new file:   file
```

I would guess that on OS X you would get that just `File` has been changed.

There's also some discussion about it [on StackOverflow](https://stackoverflow.com/q/17683458/1601695). If Documenter would set `git config core.ignorecase false`, that could fix it. Could you test it?

**Comment by haberdashPI** [comment]
I also get

```
	deleted:    File
	new file:   file
```

However I have run into issues with case and git on OS X before. I'm not sure why this particular instance doesn't seem to show the problem.

I'm not certain this is just about the case anymore. There are many folders [in this directory](https://github.com/haberdashPI/Weber.jl/tree/gh-pages/latest) that shouldn't be there if travis was using the HTML output mode. But I don't quite understand why it wouldn't be, given the contents of `make.jl`.

**Comment by mortenpi** [comment]
Which directories do you mean? As far as I can tell it all looks exactly as it should (except `Documenter.css` of course) -- one directory with `index.html` file per `.md` file.

To fix your docs there's one more thing we could try -- you could manually rename the `Documenter.css` file for `latest/` on the `gh-pages` branch. Then, re-run the last Travis job that deployed the docs -- it should deploy the latest docs again, and we should see if it renames it back (it shouldn't).

Also, unrelated to the issue: it seems that you forked `master` when you created `gh-pages`. I'm assuming that wasn't intentional. Normally one would create an orphaned branch -- no reason to have anything from the main repo on the `gh-pages` branch. An easy way to clean up would be create a new branch and `cherry-pick` all the "build based on" commits, starting with [`e7f0efc`](https://github.com/haberdashPI/Weber.jl/commits/gh-pages?after=acd255d9adfd82c0022265bf1c0d5483cdd6483f+69), I think.

**Comment by mortenpi** [comment]
> I'm not sure why this particular instance doesn't seem to show the problem.

One possibility would be that we're `git-add`ing the correct file name. Documenter `git-add`s the whole directory at once. Maybe this will fail on OS X then?

```sh
git init
mkdir dir && touch dir/File && git add dir/
git commit -m"C 1"
git rm dir/File
mkdir dir && echo "asdf" > dir/file
git add dir/
git status
```

**Comment by haberdashPI** [comment]
> To fix your docs there's one more thing we could try -- you could manually rename the Documenter.css file for latest/ on the gh-pages branch. 

Just did this. That page is now working. I am re-running travis to ensure it deploys without renaming the file.

> Which directories do you mean? As far as I can tell it all looks exactly as it should (except Documenter.css of course) -- one directory with index.html file per .md file.

Oh okay. I was confused because that's not the layout of the HTML output on my local machine. Obviously that's irrelevant, since what I did above worked.

> Also, unrelated to the issue: it seems that you forked master when you created gh-pages. I'm assuming that wasn't intentional. 

I wondered about that. No, I certainly don't need the other files if they aren't necessary. So if I follow you correctly, the sequence of commands would be:

```
git push origin --delete gh-pages
git branch -d gh-pages
git checkout gh-pages --orphan
git rev-list 0e545^..acd255 --reverse | xargs -n1 git cherry-pick -x
git push -u origin gh-pages
```

Is that right?

> One possibility would be that we're git-adding the correct file name. Documenter git-adds the whole directory at once. Maybe this will fail on OS X then?

Nope, I still get:

```
	deleted:    dir/File
	new file:   dir/file
```

**Comment by mortenpi** [comment]
> Is that right?

* I would make a backup copy of the current `gh-pages`, just in case (`git branch gh-pages-backup gh-pages`).
* You could just `push -f` into `gh-pages` afterwards, so deleting the branch on GitHub is not strictly necessary.
* `--orphan` has to be before branch name as far as I can tell (`git checkout --orphan gh-pages`)
* You need a `git reset --hard` after the `git checkout --orphan`, to clean out the working directory.
* There's a new commit on `gh-pages`, so make sure you update the commit reference of the last commit (or, apparently, you could also use the branch name, e.g. `git rev-list 0e545^..gh-pages-backup --reverse`)

**Comment by mortenpi** [comment]
I managed to reproduce the issue: https://travis-ci.org/mortenpi/Example.jl/builds/239238302#L290

However, I am still not sure where the error comes from. Could you try `git add -A .` instead of `git add dir/`? That would be the exact git command Documenter uses.

**Comment by mortenpi** [comment]
Ah, running `git rm dir/File` is why we couldn't reproduce it locally. The following should reproduce it:
```
git init
mkdir dir && touch dir/File && git add dir/
git commit -m"C 1"
rm dir/File
echo "asdf" > dir/file
git add -A .
git status
```
(Also, [Travis debug builds](https://docs.travis-ci.com/user/running-build-in-debug-mode/) FTW!)

**Comment by haberdashPI** [comment]
>  The following should reproduce it:

Yup. This is what I get.

```
	modified:   dir/File
```

Thanks for all your help!
