### ISSUE TITLE
Docstrings with LaTeX?

### ISSUE THREAD

**Issue by juliohm** [JuliaDocs/Documenter.jl#512]
Is there are way to combine `LateXStrings.jl` with `Documenter.jl` to write docstrings with LaTeX formulas that get rendered in the terminal when the user calls the `help` function? Would these strings be rendered correctly in the generated HTML?

**Comment by mortenpi** [comment]
You can do [LaTeX in docstrings](https://docs.julialang.org/en/latest/manual/documentation/#\\LaTeX-1) and [Documenter handles them fine](https://juliadocs.github.io/Documenter.jl/latest/man/latex/#latex_syntax-1). Jupyter is also able to display those equations nicely with using `?help`.

**Comment by juliohm** [comment]
Can we render any LaTeX formula? From what I understood in the documentation, we can only input latex that is recognized by the Julia tab completion in unicode?

**Comment by mortenpi** [comment]
I think using Unicode in LaTeX formulas would probably only confuse whichever LaTeX engine you're running. Documenter is only bound by what [MathJax](https://www.mathjax.org/) can do. See Documenter docs for examples.

Side note: not sure if this is where you're coming from, but the standard REPL of course fundamentally can't display equations since it's text-only.

**Comment by mortenpi** [comment]
> Side note: not sure if this is where you're coming from, but the standard REPL of course fundamentally can't display equations since it's text-only.

Well, maybe some crazy Unicode magic could be done actually. But as far as I can tell, LateXStrings is not doing that.

**Comment by juliohm** [comment]
Thank you @mortenpi , I will give it a try again. I've seen full plots rendered in ASCII and images shown on the REPL, so I wondered if LaTeX could also be rendered in a fancy way.
