### ISSUE TITLE
Warning Box to all pages of old versions

### ISSUE THREAD

**Issue by alexmorley** [JuliaDocs/Documenter.jl#539]
Is there an easy way to add a warning box to all documentation for a set of versions?

Ref: https://github.com/JuliaLang/julia/issues/22936

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing because this now happens. For things that are not `stable`, you get:

![image](https://github.com/JuliaDocs/Documenter.jl/assets/8177701/444d8f44-aab1-4e7c-9ef6-1f81b8cd70de)
