### ISSUE TITLE
Default directory (docs/ to doc/)

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#62]
A very minor thing: have `doc/` as the default directory for the documentation (instead of `docs/`)?

That is, change to `doc/` in Documenter's documentation and have the potential future `generate()` function ( #57 ) generate `doc/` by default as well.

My impression is that more packages store the docs in `doc/` currently, including Julia itself. So it would be purely in the interest of consistency, since people will most likely stick with whatever Documenter.jl suggests.

**Comment by MichaelHatherly** [comment]
The choice of `docs/` over `doc/` was intentional since I felt that the plural better implies that the folder may contain more than one document (manual, api, examples, tutorial, etc.). Perhaps that distinction isn't worth it though. We can leave this open for the time being I think and see what the general consensus is.

If it were to change then packages using `Documenter` should be updated accordingly, as was done in #51, though not quite as time-consuming I'd imagine :)

Interestingly the following two searches suggest `docs/` is more common at the moment... but perhaps the search terms could be improved.

- `doc/` https://github.com/search?q=using+language%3AJulia+path%3Adoc+-user%3AJuliaPackageMirrors&ref=searchresults&type=Code&utf8=%E2%9C%93
- `docs/` https://github.com/search?q=using+language%3AJulia+path%3Adocs+-user%3AJuliaPackageMirrors&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by mortenpi** [comment]
To me `doc` implies the uncountable "documentation", which seems fine as well. Also, somehow I have it in my head that `doc` is more standard on linux/unix, e.g. `/usr/share/doc`. But quickly looking around, python projects seem to use `docs`, for example.

Since I wanted to play around with METADATA.jl anyway, I quickly looked at the situation there:
out of the 1029 package, 223 have a `doc` or a `docs` directory in master right now, with 124 of them `doc/` and 99 `docs/`.

So, while `doc` has a tiny lead in METADATA, it's way smaller than I thought. So, I guess we can keep it open for a short while, but I now actually think that there is no reason to switch.

**Comment by MichaelHatherly** [comment]
> I guess we can keep it open for a short while

Agreed, perhaps someone will come up with a solid reason to change. Registered packages probably have a bias toward `doc` since they're generally older than `Documenter` is I suppose.

**Comment by davidanthoff** [comment]
One reason for using ``doc`` is that we already use ``test`` and not ``tests`` for tests, even though there are typically multiple tests.

**Comment by MichaelHatherly** [comment]
> One reason for using `doc` is that we already use `test` and not `tests` for tests, even though there are typically multiple tests.

Fair point.

At this point though I'd say that going through and changing packages from `docs` to `doc` is just going to be a needless change and time could be better spent with other work.

If someone *does* want to make this change badly enough then they're welcome to do it, but they'd also need to open PRs to make the change in all repos using `docs` to keep all packages using Documenter consistent with each other as much as possible.
