### ISSUE TITLE
Doc not being deployed

### ISSUE THREAD

**Issue by rveltz** [JuliaDocs/Documenter.jl#645]
Dear developers,

I am using your beautiful package for PDMP.jl but so I have not been able to update the docs online. The docs online are several months behind what is in the current sources. In the travis results, I get 

```Documenter: skipping docs deployment.```

which I don't understand.

I'd be very thankful if you can give me a hand here,

Thank you very much,

Best regards

**Comment by mortenpi** [comment]
`deploydocs` does a bunch of checks to determine whether it should deploy or not. You can add `DOCUMENTER_DEBUG` with the value `true` as an [environment variable for the Travis builds](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) which will show more details about why the deployment was skipped.

Although, AFAICT, `osname = "osx"` is why the Linux build does not deploy, and OSX builds fail [because `pip` is missing](https://travis-ci.org/rveltz/PDMP.jl/jobs/343006258#L2835-L2845).

**Comment by rveltz** [comment]
Changing `osname` into `linux` solve the issue. Thank you lot!

Also, the link **_Edit on GitHub_** does not work, it should be point to [this](https://github.com/rveltz/PDMP.jl/edit/master/docs/index.md).
Any further idea?

**Comment by mortenpi** [comment]
"Edit on GitHub" is a MkDocs configuration issue. You need to set the correct [`edit_uri`](http://www.mkdocs.org/user-guide/configuration/#edit_uri) in `mkdocs.yml`.

**Comment by rveltz** [comment]
It does not seem to be an option in [Documenter.jl](https://juliadocs.github.io/Documenter.jl/)

**Comment by mortenpi** [comment]
It's not, it's a MkDocs option. If you're using the MkDocs backend you also need to make sure the MkDocs configuration (in `mkdocs.yml`) is set up correctly. (This could probably be explained better in Documenter's manual.)
