### ISSUE TITLE
Extendable API for keywords

### ISSUE THREAD

**Issue by anthony-wang** [JuliaDocs/Documenter.jl#675]
Hi all,

We have some custom scripts in a `.jl` file that we'd like to run before building a document with `Documenter.jl`.

I'd like to ask, if there is a functionality built into `Documenter` (perhaps using the `make.jl` file), to execute these custom scripts, _before_ proceeding and building the rest of the documents? Of course, we can also execute these scripts ourselves, but this could save a bit of time :)

Thanks in advance!

**Comment by fredrikekre** [comment]
Just run your custom code in `make.jl` before you call `makedocs`?

**Comment by SimonDanisch** [comment]
Well, we'd want to replace custom keyword (basically an extension to the currently available keywords in Documenter). E.g something like `@fetch_sample_from_database: "example_code_snippet"`.
First, it would be nice to have an API in general for that, and second, now we'd need to change the folder structure a bit, to have the original files and then the preprocessed ones. Not a big deal, but maybe more people would like to have an API for this!

**Comment by KristofferC** [comment]
Just do

```
function mymakedocs(;mykwarg, kwargs...) 
    # do_stuff
    makedocs(kwargs...) 
```

?

**Comment by SimonDanisch** [comment]
By keyword I meant stuff like `@ref` `@docs` etc.
Since documenter goes through all these with a match + replace already, I thought we might as well make it extendable. Then we don't need to go through all markdown files, replace them, and pass the new files to makedocs in an extra step. As I said, not a big deal to do that - feel free to close, if you think that no one else will want to extend the set of special syntax that is accepted in markdown files ;)

**Comment by KristofferC** [comment]
It was just unclear what the feature request actually was.

**Comment by SimonDanisch** [comment]
Sorry about the confusion :) 

To make it a bit more concrete, here is an API proposal:
```Julia
custom_replacements = Dict{Regex, Function}(
    r"@fetch_sample_from_database: \"(.*)\"" => function (match)::String
        database_key = match.captures[1]
        source = find_source(global_database, database_key)
        # return a String with any markdown accepted by Documenter:
        """
        ```@example
            $source
        ```
        """
    end
)
````
And maybe pass that as keyword argument to makedocs ;)

**Comment by fredrikekre** [comment]
Sounds like this could already be done with an ```` ```@eval ```` block?

**Comment by SimonDanisch** [comment]
I guess that could be used to call the function directly! Maybe also less confusing then having a bunch of user defined custom syntax

**Comment by SimonDanisch** [comment]
I didn't like the eval block, especially since it will always be in a vanilla module, so you would always need to include some setup code into each block.

Anyways, the code for expanding examples blocks looked suspicously extendable, so I took a bit of a dive - and figured out how to introduce your own keywords:

```Julia
using Documenter
using Documenter: Selectors, Expanders, Markdown
using Documenter.Markdown: Link, Paragraph

struct DatabaseLookup <: Expanders.ExpanderPipeline end

Selectors.order(::Type{DatabaseLookup}) = 0.5
Selectors.matcher(::Type{DatabaseLookup}, node, page, doc) = false
match_kw(x::String) = ismatch(r"\@library\[example\] \"(.*)\"", x)
match_kw(x::Paragraph) = any(match_kw, x.content)
match_kw(x::Any) = false
Selectors.matcher(::Type{DatabaseLookup}, node, page, doc) = match_kw(node)

function Selectors.runner(::Type{DatabaseLookup}, x, page, doc)
    matched = nothing
    for elem in x.content
        if isa(elem, AbstractString)
            matched = match(r"\@library\[example\] \"(.*)\"", elem)
            matched != nothing && break
        end
    end
    matched == nothing && error("No match: $x")
    database_key = matched[1]
    page.mapping[x] = Markdown.Code("julia", look_up_source(database_key))
end

makedocs()
```

Looks magical? Yeah, it uses `subtypes(ExpanderPipeline)` to figure out what matchers to invoke ;)

**Comment by mortenpi** [comment]
> the code for expanding examples blocks looked suspicously extendable

That's because It was designed to be :smile: Although it's not really documented, so a thing to keep in mind is that I don't consider this public API at the moment, so it _may_ change between minor versions (although, in practice, it doesn't really).

But I am interested in making sure that Documenter would be as extensible as possible in this way, so feedback and thoughts are most welcome. Gathering use cases is really useful to make sure we get a good API for this.

Other than that, I'd say the Selectors API is the best way to implement what you need, so I guess this issue can be closed?
