### ISSUE TITLE
Move package to an org

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaDocs/Documenter.jl#69]
Might be worth moving the package to a GitHub org, rather than have it live in my account. Hopefully that would make development more open/approachable for others. `JuliaDocs` seems like an appropriate name for such an org. (Docile and Lexicon could move as well once they get rewritten for new purposes in `0.5`.)

Probably best to merge the two current PRs first to avoid any headaches.

Possible problem may be the current practice of installing `Documenter` with `Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl")`, though I believe GitHub should handle the URL redirection for us.

cc @mortenpi

**Comment by MichaelHatherly** [comment]
There's probably some parts of `Documenter` that could be split out into smaller packages after the move, though not a high priority right now.

**Comment by mortenpi** [comment]
I don't actually have very strong opinion on the matter, it's pretty common for packages to live in quite random places. But I can see how it could give a slightly more official feel to it and perhaps make it easier for people to find packages. So.. once it's more than one package, then it would probably make sense to have them under the `JuliaDocs` banner so that they wouldn't be scattered.

I quickly tried to transfer ownership to an organization, and yes, GitHub nicely sets up a redirect which works for cloning as well. So that shouldn't be a problem.. although I guess you can't fork it to yourself, but that shouldn't be necessary anyway.

**Comment by MichaelHatherly** [comment]
> although I guess you can't fork it to yourself

Yeah, that would mess things up.

**Comment by tkelman** [comment]
> Yeah, that would mess things up.

Would have to test on something less consequential if the answer is no, but I wonder whether github is prescient enough to warn you if you try to do this?

**Comment by MichaelHatherly** [comment]
So far everything has worked fine I think -- apart from all the repo traffic stats vanishing.

It's mentioned in github's [help page](https://help.github.com/articles/about-repository-transfers/) on the topic that adding a new repo would stop the redirects.

**Comment by tkelman** [comment]
Yeah I've seen that creating a new repo where a relocated repo used to be does break the redirect, though if you're fast about deleting the new copy it seems the redirect comes back. I wonder what that would do to existing clones with remotes pointing to the old url, if something new shows up in its place.
