### ISSUE TITLE
Default style overhaul

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#722]
It is probably fair to say that the default style/CSS of Documenter’s HTML build could be improved. The current style is based on the old Sphinx style with minor modifications. Over time there have been various suggestions (e.g. #667, #668) and issues (e.g. #618, #638) reported that have to do with the style.

While improvements are definitenly most welcome, small design changes can be a bit problematic since whether or not they are an improvement is pretty subjective. Instead, doing a single bigger overhaul of the general look might be a better approach, since it would allow us to keep the whole design consistent etc.

This issue is very much up for grabs. Also, I'd be very happy to delegate the visual design decisions to someone else (but it should probably be a single person, since I don't think design-by-committee really works).

The philosophy is that Documenter’s default style should be the look-and-feel of the [main Julia manual](https://docs.julialang.org/). So this would directly affect the main manual in a pretty significant way.

**For potential contributors:** a good way to approach this would be to create HTML/CSS mockup first, based on e.g. a few pages in the Julia manual, which we could then iterate on.

There was also a suggestion to use [Bootstrap](https://getbootstrap.com/) as the underlying framework (#626), with some work done on that front. The use of a framework is, I think, a good idea, since it would do a lot of work for us (e.g. mobile UI/UX).

**Comment by tpoisot** [comment]
A quick suggestion -- there are two separate components on the style: the page layout (which should be common across most of the Julia universe documentation), and the specific styling (which can vary, because specific packages may want to develop their own identity).

I would be in favor of an intermediate solution that would

1. have a `documenter.css` file for layout
2. have a `style.css` file for visuals

Users can rewrite the `style.css` if needed for their projects
