### ISSUE TITLE
ERROR: UndefVarError: [name of imported module] not defined

### ISSUE THREAD

**Issue by miguelmorin** [JuliaDocs/Documenter.jl#741]
I have a sample module in `src/my_module.jl` that imports DataFrames:

````
module my_module

using DataFrames

"""
    dummy()

Dummy function

# Examples
```jldoctest
julia> df = convert(DataFrame, [1 2 3; 4 5 6]);
```
"""
function dummy()
    return nothing
end

end

```
````

This works in the Julia console:
```
julia> include("src/my_module.jl");df = convert(DataFrame, [1 2 3; 4 5 6])
2×3 DataFrames.DataFrame
│ Row │ x1 │ x2 │ x3 │
├─────┼────┼────┼────┤
│ 1   │ 1  │ 2  │ 3  │
│ 2   │ 4  │ 5  │ 6  │
```

However, with a plain `docs/src/index.md` to run doc-tests:

````
```@meta
DocTestSetup = quote
    using my_module
end
```

```@autodocs
Modules = [my_module]
```
````
the doc-test fails with `ERROR: UndefVarError: DataFrame not defined`. I need to include `using DataFrames` in `DocTestSetup` to make it work:
````
```@meta
DocTestSetup = quote
    using DataFrames
    using my_module
end
```
````

Can Documenter include the same modules imported by the module under test?

**Comment by mortenpi** [comment]
> Can Documenter include the same modules imported by the module under test?

No. Doctest code runs in its own module, which is empty unless explicitly initialised with either a `DocTestSetup` or in a previous named doctests. Adding `using DataFrames` into a `DocTestSetup` is how it should be done here.

**Comment by miguelmorin** [comment]
Thanks @mortenpi. Can this become a future enhancement?

**Comment by mortenpi** [comment]
> Can this become a future enhancement?

It definitely should not be done automatically, since having doctests run in a clean module is a feature. Maybe it could be a keyword argument? We would need to figure out which module contains the docstring and then loop through the `names` in the module, I guess?

Alternatively, maybe we could have some sort of a module-wide `DocTestSetup`.. or maybe an option to pick a `DocTestSetup` from some global database.

Still, not entirely sure how good of an idea / feasible either of them would be.
