### ISSUE TITLE
Offline documentation search error: `Number of results: loading...`

### ISSUE THREAD

**Issue by miguelmorin** [JuliaDocs/Documenter.jl#743]
I compiled the documentation locally for offline use with `make docs`. I open `index.html` and search for `html`. I get 56 results after a few seconds. But if I search for `rm` (for `Pkg.rm`), I get `Number of results: loading...` and it stays there. I can overwrite the search term and do other searches that work, such as `html` or `reshape`.

Julia is 0.6.3, Safari is Version 11.1.1 (13605.2.8), macOS is 10.13.5 (17F77).

**Comment by mortenpi** [comment]
It seems to work fine for me (Linux / Chrome). Does anything show up in the [developer tools](https://superuser.com/questions/302014/safari-web-developer-tools) console?

**Comment by miguelmorin** [comment]
Yes, the search for `html` and `reshape` show nothing in the Console, the search for `rm` shows these two errors:

```
[Error] TypeError: undefined is not an object (evaluating 'f._index')
	query (lunr.min.js:1:12802)
	update_search (search.js:197)
	update_search_box (search.js:230)
	dispatch (jquery.min.js:3:10321)

[Error] TypeError: undefined is not an object (evaluating 'f._index')
	query (lunr.min.js:1:12802)
	update_search (search.js:197)
	update_search_box (search.js:230)
	e (lodash.min.js:2:11219)
	a (lodash.min.js:2:11480)
	f (lodash.min.js:2:11426)
```

**Comment by mortenpi** [comment]
Sorry for not getting back to this issue earlier. But I noticed that the latest lunr.js (v2.3.1) included a workaround for a suspiciously similar issue (olivernn/lunr.js#279). I've built the manual with both the current and updated lunr. Could you check if it fixes the issue? For that

* Check if you can reproduce the issue with my build here: http://mortenpi.eu/julia/manual-issue743-lunr-2.1.3/
* And see if the issue is gone with this build: http://mortenpi.eu/julia/manual-issue743-lunr-2.3.1/

In case you can only repro the issue locally, then could you replace the `doc/_build/en/assets/search.js` file with [this version](http://mortenpi.eu/julia/manual-issue743-lunr-2.3.1/assets/search.js), force refresh and see if the issue is gone? (The difference is the lunr version on line 42.)

**Comment by miguelmorin** [comment]
Following the same steps with [your first build](http://mortenpi.eu/julia/manual-issue743-lunr-2.1.3/), the page now refreshes when I type `rm` and shows results I would not expect:
```
Number of results: 248

Noteworthy differences from R (section)
Base.Checked.sub_with_overflow (function)
Base.Checked.add_with_overflow (function)
```

I still get a similar error in the console:
```
[Error] TypeError: undefined is not an object (evaluating 'f._index')
	query (lunr.min.js:1:12802)
	update_search (search.js:197)
	update_search_box (search.js:237)
	e (lodash.min.js:2:11219)
	a (lodash.min.js:2:11480)
	f (lodash.min.js:2:11426)
```

In addition, I get these two load errors before the above error:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (versions.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (siteinfo.js, line 0)
```

With [your second build](http://mortenpi.eu/julia/manual-issue743-lunr-2.3.1/), I see the result I want at the top:
```
Number of results: 175

Removing packages (section)
Pkg.PackageMode (type)
Interpolation (section)
```
and the console shows only load errors:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (siteinfo.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (versions.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)
```
