### ISSUE TITLE
Doc-testing: module name appears 6 times

### ISSUE THREAD

**Issue by miguelmorin** [JuliaDocs/Documenter.jl#757]
In this [StackOverflow answer](https://stackoverflow.com/questions/50768111/julia-documenter-missing-docstring/51207534#51207534) with a setup for doc-testing, I use the name `my_module` six times. The file `docs/make.jl` is:

    using Documenter, my_module
    
    makedocs(
        modules = [my_module],
        format = :html,
        sitename = "my_module.jl",
        doctest = true
    )

The file `docs/src/index.md` is:

    # Documentation

    ```@meta
    CurrentModule = my_module
    DocTestSetup = quote
    	import my_module
    end
    ```
    
    ```@autodocs
    Modules = [my_module]
    ```

This increases the chances of typos and bugs. I believe Python would take the module name zero times or once. Could `Documenter.jl` do something similar?

**Comment by mortenpi** [comment]
Apologies for not replying to this earlier.

I don't really see how we could improve on this though. In each case `my_module` specifies a pretty distinct setting and I don't think we should make too many implicit assumptions. E.g. just because you have `CurrentModule = my_module`, doesn't necessarily mean that you want `DocTestSetup` to import it.

We could perhaps provide some shorthands, but I can't really think of any at the moment.

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing as stale. This doesn't seem like a high-priority to fix, and no one else has complained since. It's also a "write once, read many times" thing, so the risk of making typos seems low. (And you'll get a warning or an error if they're incorrect.)
