### ISSUE TITLE
```julia code block has no syntax highlighting

### ISSUE THREAD

**Issue by Helveg** [JuliaDocs/Documenter.jl#768]
The documentation [here](https://juliadocs.github.io/Documenter.jl/stable/man/syntax/#@example-block-1) lead me to believe that Documenter has syntax highlighting for julia, is this the case? If so, the codeblocks that I encapsulate with 
```
```julia 
function foo(bar)

end
`` `
```
, which I view locally with a Chrome extension called Markdown Viewer does not display any julia highlighting. Does that have something to do with the extension or am I missing something? If it has to do with the extension, where can I host these files to enable the julia highlighting? Is that something provided by the GitHub Pages recommended in the documentation?

**Comment by fredrikekre** [comment]
That is not a julia code block though.

**Comment by Helveg** [comment]
How so @fredrikekre? I updated my post in case you were talking about the lack of linebreaks.

**Comment by mortenpi** [comment]
I am not sure if this question is really Documenter-related. If you want highlighting for the `julia` block in an Markdown viewer, it has to be supported by that viewer. Documenter can't really help here.

FWIW: [Markdown Viewer](https://github.com/simov/markdown-viewer) (is that the one you mean?) should have Julia highlighting, because it using [prismjs](https://prismjs.com/#languages-list), which appears to support Julia. But you need to ask them why it is not working.

**Comment by Helveg** [comment]
Ok, I didn't know the highlighting was done by the viewer, it should've been obvious from the .md files though, sorry.
