### ISSUE TITLE
Remove reference to Pkg.dir

### ISSUE THREAD

**Issue by ararslan** [JuliaDocs/Documenter.jl#783]
We use the following code here to get the root directory for a package so that we can find its documentation directory:
```julia
    docroot = if dir === nothing
        pkgdir = Pkg.dir(pkgname)
        if !isdir(pkgdir)
            error("Unable to find package $(pkgname).jl at $(pkgdir).")
        end
        joinpath(pkgdir, "docs")
    else
        dir
    end
```
Note the reference to `Pkg.dir`. What's the correct way to replace this? It would not be that straightforward using `pathof`, since it requires a binding to the module itself, but all we have at this point is a string containing the package's name.

This is required in order to deploy the 1.0 documentation.

cc @StefanKarpinski @KristofferC

**Comment by fredrikekre** [comment]
fixed

**Comment by andyferris** [comment]
The documentation [here](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/) still leads new users (like me!) to problems using `Pkg.dir` instead of `pathof` on travis. It would be nice to fix that - I'm not sure if those docs are designed to be valid for v0.6 users still, so I didn't make a PR...

**Comment by mortenpi** [comment]
It has been fixed on master: https://juliadocs.github.io/Documenter.jl/dev/man/hosting/
