### ISSUE TITLE
Documenter bug? `_` in links changed to `*` when building

### ISSUE THREAD

**Issue by mkborregaard** [JuliaDocs/Documenter.jl#820]
Specifically, the documentation for Plots now looks like this
![skaermbillede 2018-08-27 kl 10 17 02](https://user-images.githubusercontent.com/8429802/44648754-5f37de00-a9e2-11e8-9187-5a44e54c4036.png)

When I look at the generated html, I see that the link `<iframe src="../supported_types.html"` in the markdown file is changed to `<iframe src="../supported*types.html"` in the generated html, invalidating the link.

**Comment by mortenpi** [comment]
This not stricly speaking a bug. The problem is that Documenter can't actually handle raw HTML in its input, since the Markdown parser in base doesn't handle it (#517, JuliaLang/julia#17837). It can occasionally work in the `.md` -> `.md` case, as long as there is no way of parsing the HTML as Markdown. But in this case it is interpreting the underscores to mean emphasis, and when printing Documenter uses `*` instead.

The correct solution here is to wrap the `<iframes>` in [at-raw blocks](https://juliadocs.github.io/Documenter.jl/dev/man/syntax/#@raw-format-block-1):

````
```@raw html
<iframe ...>
```
````

That makes sure that the HTML does not get parsed as Markdown gets copied verbatim.

**Comment by mkborregaard** [comment]
Yay, thanks a lot!
