### ISSUE TITLE
Decouple build process from deployment details

### ISSUE THREAD

**Issue by darwindarak** [JuliaDocs/Documenter.jl#88]
[`Utilities.getremote(root)`](https://github.com/JuliaDocs/Documenter.jl/blob/16f3d743ec1bdbcc447e7b3128f354f154f157fd/src/modules/Documents.jl#L111) is getting called whenever a document is created, regardless of whether or not the docs have been setup for deployment.  Is there an option to turn this off so the docs can be built just locally?

**Comment by MichaelHatherly** [comment]
The call is for inserting source links into the generated docs and isn't really part of the deployment phase.

Is `makedocs` failing to run due to a missing remote `origin`? We could just fall back to the local part if it's not available, or not insert the link at all in when it's not available.

I'd like to avoid having too many user settings in `makedocs` if possible.

**Comment by darwindarak** [comment]
Yes, it was a problem with missing `origin`.  But even after I added an origin to the repository, it still failed due to `no remote repository found`, since it wasn't a GitHub repo.

**Comment by mortenpi** [comment]
Since I presume that this is a private repository, I am curious what would
your expectation be regarding source links. Should they work or be disabled
in this case?

We could add a flag to disable them altogether or just somehow gracefully
deal with source links that can't be resolved.

On Thu, Jun 9, 2016 at 3:31 PM, Darwin Darakananda <notifications@github.com

**Comment by darwindarak** [comment]
I think it's too much to ask for the source links to work with all types of repository hosting.  If the repository is local or hosted privately, I would not expect the source links to work.
