### ISSUE TITLE
Add JSON rendering.

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaDocs/Documenter.jl#89]
I came across Elm's JSON output for docs recently: http://package.elm-lang.org/help/docs-preview

Might be interesting to generate JSON as one of the possible outputs at some point.

**Comment by mortenpi** [comment]
Do you have a specific format (schema?) in mind or should we invent a custom structure for the JSON file?

But a possible application that I would like to see is to have single site with package documentations, including cross package search and references. Then adding a package there could be just a matter of adding a JSON file. It would also decouple the "data" (documentation) from the presentation. I am wondering though.. maybe XML would be more appropriate for this.

**Comment by MichaelHatherly** [comment]
No format in mind at the moment. 

> single site with package documentations, including cross package search and references.

Yup, that's the idea, should be possible I think.

**Comment by odow** [comment]
_I'm doing a triage of open documenter issues and closing issues that are stale. If I've made a mistake, please re-open_

Closing as stale. It'd be nice to have everything in a single file for something like MultiDocumenter, but there are too many edge-cases (big heavy assets like images?). We'd also have to define our own schema, which seems like a heavy lift. Also, no one else has asked for this since 2016, so it doesn't seem like a high priority.
