### ISSUE TITLE
`@autodocs` outputs wrong order for functions in compact "assignment form"

### ISSUE THREAD

**Issue by mroavi** [JuliaDocs/Documenter.jl#964]
I am using `@index` and `@autodocs` in the same .md file. See below how the resulting order is different for the output of both commands despite the fact that the `Order` field for both commands is exactly the same. 
![image](https://user-images.githubusercontent.com/19517248/52901133-496fdc80-31ff-11e9-81bb-b323b0436899.png)
I suspect that the reason is that `@autodocs` is not interpreting functions written in compact "assignment form" as functions, i.e. functions written like this:
```
"""
Helper function to construct 1x1 Matrix
"""
mat(sc) = reshape([sc],1,1)
```

**Comment by laborg** [comment]
The ordering problems also include abstract types (e.g. an abstract type is correctly sorted in the `@index` but not by `@autodocs`)

**Comment by laborg** [comment]
This has nothing to do with abstract types or one line function definitions, but it is by design: In `Expanders.jl` there is this line
https://github.com/JuliaDocs/Documenter.jl/blob/2180a0efa7748ca5059a1c33e772e6de8013e35f/src/Expanders.jl#L441
explicitly creating an ordering incompatible with the index.

Could this be removed?
