### ISSUE TITLE
Deployment on other CI systems

### ISSUE THREAD

**Issue by mortenpi** [JuliaDocs/Documenter.jl#988]
Currently we officially only support deploying GitHub repositories on Travis CI to GitHub pages. `deploydocs` also relies on Travis-specific environment variables mostly. We should probably support more Git hosting and CI systems (documentation + generalized API where necessary). The following come to mind:

- [ ] GitLab: has its own CI and Pages
- [ ] BitBucket: has its own CI (Pipelines) and Pages

In the meantime, there are a few examples of how to work around current limitations:

* An example Documenter setup on BitBucket using BitBucket Pipelines and BitBucket Pages: https://bitbucket.org/mortenpi/documenterexample.jl/
* An example of Julia and Documenter on GitLab: https://gitlab.com/tkpapp/GitlabJuliaDemo.jl

**Comment by tkf** [comment]
FYI I added GitLabPages plugin to use Documenter.jl in GitLab repository created by PkgTemplates.jl: https://github.com/invenia/PkgTemplates.jl/pull/54

However, it only publishes `dev` document.  It would be nice if Documenter.jl supports versioned documentation on GitLab pages.

**Comment by mortenpi** [comment]
How does GitLab handle tags? Can you run CI on tags?

**Comment by tkf** [comment]
Yes.  It looks like you can detect it with `CI_COMMIT_TAG` https://docs.gitlab.com/ee/ci/variables/README.html#predefined-environment-variables

I think a harder (?) issue is that GitLab pages is not a git branch as in GitHub.  You create a directory `public` in your repository and the whole content is reflected to the GitLab pages (IIUC).  It's actually convenient for publishing a single document (see how it's done in PkgTemplates: https://github.com/invenia/PkgTemplates.jl/blob/901a0a3d7139588819bad19acfc891a63bda7637/defaults/gitlab-ci.yml#L20)  However, I think it's a bit more challenging to update a part of it (e.g., `public/v1.2`) since you need to store the whole content somewhere and retrieve it in the CI job.  I guess you can create (say) `gl-pages` branch like `gh-pages` in GitHub and check it out at `public`.  But I'm not familiar enough with the whole GitLab interface to know if there is a better way to do it.

**Comment by marekdedic** [comment]
I was just about to create a new issue suggesting adding support for Circle CI....

I think some of the environment variable checks could be done in the CI configuration - e. g. checking for pull requests isn't necessary if you only run the deploy job on the master branch...

**Comment by christopher-dG** [comment]
To add to this: GitHub Actions will be generally available soon and it would be nice be able to deploy to GitHub Pages from there.

**Comment by davidanthoff** [comment]
Just to second GitHub Actions! We have a nice set of actions in the works right now (https://github.com/julia-actions), and adding one for doc build and deploy would be great.

**Comment by sebastiangrimberg** [comment]
> However, it only publishes `dev` document. It would be nice if Documenter.jl supports versioned documentation on GitLab pages.

Coming across this looking for a solution for versioned Documenter.jl output on Gitlab pages. Does anyone have any update or idea if this is possible yet?

**Comment by mortenpi** [comment]
This issue is a little dated, so I'll go ahead an close it. We do now have some built-in support for other CI systems: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Deployment-systems

I don't think [the GitLab one](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Documenter.GitLab) supports pushing to GitLab Pages though.
